### ISSUE TITLE
Method not found get_Body

### ISSUE THREAD

**Issue by shravan2x** [microsoft/playwright-dotnet#1354]
I ran this fairly simple code:
```
using IPlaywright? playwright = await Playwright.CreateAsync();
await using IBrowser? browser = await playwright.Firefox.LaunchAsync(headless: false);

IBrowserContext? context = await browser.NewContextAsync(viewport: new ViewportSize { Width = 1920, Height = 1080 });
IPage? page = await context.NewPageAsync();
await page.GoToAsync("https://google.com/", LifecycleEvent.DOMContentLoaded);
await Task.Delay(5000);
await page.EvaluateAsync("() => {document.querySelector('input[name=\"code\"]').value = 'text one'; return '';}");
```

and got this exception:
```
System.MissingMethodException: Method not found: 'Esprima.Ast.NodeList`1<Esprima.Ast.IStatementListItem> ByRef Esprima.Ast.Script.get_Body()'.
   at PlaywrightSharp.Helpers.StringExtensions.IsJavascriptFunction(String script, Boolean retry, Boolean checkExpression)
   at PlaywrightSharp.Frame.EvaluateAsync(Boolean isPageCall, String script) in /home/runner/work/playwright-sharp/playwright-sharp/src/PlaywrightSharp/Frame.cs:line 672
```

This is with Playwright 0.192.0. Am I missing something?

**Comment by avodovnik** [comment]
I couldn't repro the issue with your code. When I run it, I get 

```
    PlaywrightSharp.PlaywrightSharpException : Evaluation failed: document.querySelector(...) is null
```

Which is expected, considering the selector & the page.

Here's what I tried:

```csharp
var context = await browser.NewContextAsync(viewport: new ViewportSize { Width = 1920, Height = 1080 });
var page = await context.NewPageAsync();
await page.GoToAsync("https://google.com/", LifecycleEvent.DOMContentLoaded);
await page.ClickAsync("#zV9nZe");

await page.EvaluateAsync("() => {document.querySelector('input[name=\"q\"]').value = 'text one'; return '';}");
var result = await page.EvaluateAsync("() => {document.querySelector('input[name=\"q\"]').value = 'test two'; return ''; }");
result = await page.EvaluateAsync("() => { document.querySelector('input[id=\"sb_form_q\"]').value = 'test two'; return null; }");
```

That said, depending on what you want to achieve, I would use either `FillAsync` or `TypeAsync` and fill out the value, example:

```csharp
var context = await browser.NewContextAsync(viewport: new ViewportSize { Width = 1920, Height = 1080 });
var page = await context.NewPageAsync();
await page.GoToAsync("https://google.com/", LifecycleEvent.DOMContentLoaded);
await page.ClickAsync("#zV9nZe");

await page.FillAsync("input[name=q]", "this is a value");
await page.TypeAsync("input[name=q]", "Text text test");
```

Let me know if that helps.
