### ISSUE TITLE
Using in CI (GitHub Actions) fails

### ISSUE THREAD

**Issue by timheuer** [microsoft/playwright-dotnet#1523]
I have a relatively simple script within a test class:

```
[TestMethod]
        public async Task TestMethod1()
        {
            using var playwright = await Playwright.CreateAsync();
            await using var browser = await playwright.Chromium.LaunchAsync();// new BrowserTypeLaunchOptions() { Headless = false });

            var context = await browser.NewContextAsync(new BrowserNewContextOptions()
            {
                Locale = "de-DE"
            });

            var page = await context.NewPageAsync();
            await page.GotoAsync("https://tacticsview.azurewebsites.net");
            await page.WaitForLoadStateAsync(LoadState.DOMContentLoaded);
            await page.ClickAsync("#navlink-consider");
            await page.WaitForLoadStateAsync(LoadState.DOMContentLoaded);
            await page.ScreenshotAsync(new PageScreenshotOptions() { Path = "screenshots/consider-german.png" });
            await page.ClickAsync("#navlink-approved");
            await page.WaitForLoadStateAsync(LoadState.DOMContentLoaded);
            await page.ScreenshotAsync(new PageScreenshotOptions() { Path = "screenshots/approved-german.png" });
        }
```

When running in CI using GitHub Actions it fails:
```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed TestMethod1 [33 s]
  Error Message:
   Test method TestProject1.UnitTest1.TestMethod1 threw exception: 
System.TimeoutException: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "#navlink-consider"
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
  Stack Trace:
      at Microsoft.Playwright.Transport.Connection.SendMessageToServerAsync[T](String guid, String method, Object args)
   at TestProject1.UnitTest1.TestMethod1() in /home/runner/work/WebApplication73/WebApplication73/TestProject1/UnitTest1.cs:line 24
   at TestProject1.UnitTest1.TestMethod1() in /home/runner/work/WebApplication73/WebApplication73/TestProject1/UnitTest1.cs:line 29
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)
```
The action script looks like this:
```
jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Setup Playwright
      run: |
        dotnet tool install -g Microsoft.Playwright.CLI
        npx playwright install-deps chromium

    # note this step is needed because the latest chromium is not being installed with the above commands
    - name: Ensure latest Chromium
      run: |
        npm i -D playwright
```

**Comment by timheuer** [comment]
was an issue in deployment...resolved

**Comment by hlaueriksson** [comment]
Thanks for this recipe on how to setup Playwright in GitHub Actions 🙏
