### ISSUE TITLE
Playwright in F# scripts

### ISSUE THREAD

**Issue by marcingolenia** [microsoft/playwright-dotnet#1590]
Hello, 
did You try to run playwright from F# script? I have something like this;
```fsharp
#r "nuget: Microsoft.Playwright"
#r "nuget: Ply"

open Microsoft.Playwright
open FSharp.Control.Tasks

task {
    use! web = Playwright.CreateAsync()
    printfn "test"
} |> Async.AwaitTask |> Async.RunSynchronously
```
when I try to run this using
```bash
dotnet fsi script.fsx
```
I get;
```bash
System.AggregateException: One or more errors occurred. (Driver not found: /home/mgolenia/.nuget/packages/microsoft.playwright/1.12.2/lib/net5.0/.playwright/node/linux/playwright.sh)
 ---> Microsoft.Playwright.PlaywrightException: Driver not found: /home/mgolenia/.nuget/packages/microsoft.playwright/1.12.2/lib/net5.0/.playwright/node/linux/playwright.sh
   at Microsoft.Playwright.Helpers.Paths.GetExecutablePath()
   at Microsoft.Playwright.Transport.Connection.GetProcess()
   at Microsoft.Playwright.Transport.Connection..ctor()
   at Microsoft.Playwright.Playwright.CreateAsync()
   at FSI_0002.it@67.Invoke(Unit unitVar)
   at Ply.TplPrimitives.ContinuationStateMachine`1.System-Runtime-CompilerServices-IAsyncStateMachine-MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 337
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInAnotherThread[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 851
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 886
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1148
   at <StartupCode$FSI_0002>.$FSI_0002.main@()
Stopped due to error
```
I am on Linux Ubuntu Groovy 20.10. Also I was not able to install dependencies;
```bash
$ playwright install-deps
Please make sure Playwright is installed and built:
   dotnet add package Microsoft.Playwright
   dotnet build
```
Some hints will be helpful, thanks!

**Comment by avodovnik** [comment]
That looks like you're running the scripting side, instead of building. We've recently shipped a fix that might help with this - can you try using the pre-release version (`1.13-next-1`)? That should default to looking for the `.playwright` folder in the `nuget` cache, which is where it might actually find it for your case. 

The problem is, FWIW, that we rely on the `build` task, to copy `.playwright` to the `bin/Debug/{framework}` location, but because you're running `fsi`, that won't happen. You can manually copy it from `%USERPROFILE%\.nuget\packages\microsoft.playwright\1.13.0-next-1\.playwright` or `%USERPROFILE%\.nuget\packages\microsoft.playwright\1.12.2\Drivers` if you're using the current stable version.

**Comment by marcingolenia** [comment]
@avodovnik Perfect! That did it! 
After I moved to the preview version You have mentioned I came across next problem;
```bash
System.AggregateException: One or more errors occurred. (Failed to launch chromium because executable doesn't exist at /home/mgolenia/.cache/ms-playwright/chromium-888113/chrome-linux/chrome
Try re-installing the browsers running `playwright.cmd install` in windows or `./playwright.sh install` in MacOS or Linux.)
 ---> Microsoft.Playwright.PlaywrightException: Failed to launch chromium because executable doesn't exist at /home/mgolenia/.cache/ms-playwright/chromium-888113/chrome-linux/chrome
Try re-installing the browsers running `playwright.cmd install` in windows or `./playwright.sh install` in MacOS or Linux.
   at Microsoft.Playwright.Transport.Connection.SendMessageToServerAsync[T](String guid, String method, Object args)
```
It was enough to execute the script (one-time action);
```bash
~/.nuget/packages/microsoft.playwright/1.13.0-next-1/.playwright/node/linux/playwright.sh install
```
Then this worked like a charm:
```fsharp
#r "nuget: Microsoft.Playwright, 1.13-next-1"
#r "nuget: Ply"

open Microsoft.Playwright
open FSharp.Control.Tasks

task {
    use! web = Playwright.CreateAsync()
    let! browser = web.Chromium.LaunchAsync()
    let! page = browser.NewPageAsync()
    let! _ = page.GotoAsync("https://playwright.dev/dotnet")
    let screenshotOptions = PageScreenshotOptions()
    screenshotOptions.Path <- "a_screenshot.png"
    let! _ = page.ScreenshotAsync(screenshotOptions)
    printfn "Success"
} |> Async.AwaitTask |> Async.RunSynchronously
```
