### ISSUE TITLE
Azure Devops Pipeline Issues

### ISSUE THREAD

**Issue by srpeirce** [microsoft/playwright-dotnet#1596]
Hello,

I am having difficulty running tests in Azure Devops Pipeline.

Running net5.0. Tried versions 1.12.2 and 1.13.0-next.

Have successfully installed the dotnet global tool and drivers:
```
    - task: DotNetCoreCLI@2
       displayName: 'Install PlayWright CLI'
       inputs:
         command: 'custom'
         custom: 'tool'
         arguments: 'install --global Microsoft.Playwright.CLI'
     - task: CmdLine@2
       displayName: 'Install PlayWright Broswer Drivers'
       inputs:
         script: 'playwright install'
```

I just get this error. I find it strange to see the `Win32Exception` as running against `ubuntu-latest`.
```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:00.74]     P4.Web.Public.UiTests.UnitTest1.Test1 [FAIL]
  Failed P4.Web.Public.UiTests.UnitTest1.Test1 [53 ms]
  Error Message:
   System.ComponentModel.Win32Exception : Permission denied
  Stack Trace:
     at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.Playwright.Transport.Connection..ctor()
   at Microsoft.Playwright.Playwright.CreateAsync()
   at P4.Web.Public.UiTests.UnitTest1.Test1() in /home/vsts/work/1/s/P4.Web.Public.UiTests/UnitTest1.cs:line 22
--- End of stack trace from previous location ---
```

**Comment by srpeirce** [comment]
Have also tried using the container as per instructions here: https://playwright.dev/dotnet/docs/ci#azure-pipelines

```
pool:
      name: Azure Pipelines
      vmImage: ubuntu-latest
    container: mcr.microsoft.com/playwright:focal
```

**Comment by aslushnikov** [comment]
@srpeirce do you have a link to your azure pipeline to look at?

**Comment by srpeirce** [comment]
Thank you for response.  I've just come back to this fresh and think I might of found my issue. I'll confirm and get back shortly.

**Comment by srpeirce** [comment]
Okay, yah I got it working quite simply. I think I was adding complexity last night and had gotten confused. 

This works:
```yaml
- job: 'UiTests'
    displayName: 'Dev UI Tests'
    dependsOn: 'DeployAzure'
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Dotnet Restore'
      inputs:
        command: 'restore'
        projects: 'P4.Web.Public.UiTests'
        feedsToUse: 'select'
        vstsFeed: '[private nuget feed]'
    - task: DotNetCoreCLI@2
      displayName: 'Dotnet Build'
      inputs:
        command: 'build'
        projects: 'P4.Web.Public.UiTests'
        arguments: '--no-restore --configuration $(buildConfiguration)'
    - task: DotNetCoreCLI@2
      displayName: 'Install PlayWright CLI'
      inputs:
        command: 'custom'
        custom: 'tool'
        arguments: 'install --global Microsoft.Playwright.CLI'
    - task: CmdLine@2
      inputs:
        script: 'playwright install'
    - task: DotNetCoreCLI@2
      displayName: 'UI Test'
      inputs:
        command: 'test'
        projects: 'P4.Web.Public.UiTests'
        arguments: '--no-build --no-restore --configuration $(buildConfiguration) --filter Category="UiTest" -e BaseUrl="https://{domain}"'
        testRunTitle: 'Unit Tests'
```
