### ISSUE TITLE
[Feature]: Provide a .NET Docker image

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright-dotnet#1611]
### Feature request

Provide a Docker image to make Playwright for .NET work with Docker out of the box. Similarly to what was done for Playwright for Java.

**Comment by LGinC** [comment]
```dockerfile
FROM mcr.microsoft.com/playwright
RUN apt-get update; \
    apt-get install wget apt-transport-https && \
    wget https://packages.microsoft.com/config/ubuntu/20.10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    rm packages-microsoft-prod.deb && \
    apt-get update && apt-get install -y dotnet-runtime-5.0 && \
    apt-get clean
WORKDIR /app
COPY . .
ENTRYPOINT ["dotnet", "xxx.dll"]
```
.net 5.0,  emmm.... size of image is 1.8G

**Comment by h0730303779** [comment]
> ```dockerfile
> FROM mcr.microsoft.com/playwright
> RUN apt-get update; \
>     apt-get install wget apt-transport-https && \
>     wget https://packages.microsoft.com/config/ubuntu/20.10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
>     dpkg -i packages-microsoft-prod.deb && \
>     rm packages-microsoft-prod.deb && \
>     apt-get update && apt-get install -y dotnet-runtime-5.0 && \
>     apt-get clean
> WORKDIR /app
> COPY . .
> ENTRYPOINT ["dotnet", "xxx.dll"]
> ```
> 
> .net 5.0, emmm.... size of image is 1.8G

![image](https://user-images.githubusercontent.com/16299810/132552045-ca2e7d8e-f230-406b-a73e-a2695a1f0dc3.png)

这个dockerfile 能用么 我直接扑街啊.

**Comment by pablopioli** [comment]
The official image is based on Ubuntu 20.04, what I use is

```
FROM mcr.microsoft.com/playwright:focal AS playwright
RUN apt-get update \
    && apt-get install -y wget \
    && wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && apt-get update \
	&& apt-get install dumb-init \
    && apt-get install -y apt-transport-https \
    && apt-get install -y aspnetcore-runtime-5.0 \
    && apt-get remove -y wget
COPY --from=build /publish/ /app/
RUN chown -R pwuser:pwuser /app
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["dotnet", "/app/xxx.dll"]
```

What I can make it 

> 
> 
> > ```dockerfile
> > FROM mcr.microsoft.com/playwright
> > RUN apt-get update; \
> >     apt-get install wget apt-transport-https && \
> >     wget https://packages.microsoft.com/config/ubuntu/20.10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
> >     dpkg -i packages-microsoft-prod.deb && \
> >     rm packages-microsoft-prod.deb && \
> >     apt-get update && apt-get install -y dotnet-runtime-5.0 && \
> >     apt-get clean
> > WORKDIR /app
> > COPY . .
> > ENTRYPOINT ["dotnet", "xxx.dll"]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > .net 5.0, emmm.... size of image is 1.8G
> 
> ![image](https://user-images.githubusercontent.com/16299810/132552045-ca2e7d8e-f230-406b-a73e-a2695a1f0dc3.png)
> 
> 这个dockerfile 好像用不起来, 我直接扑街啊. 还有别的办法不帮忙指点一下

You must be using an old version of Playwright for net. The browsers don't get downloaded here anymore.
The docker image now puts them in /ms-playwright

**Comment by pablopioli** [comment]
The Docker image is necessary, or at least basic documentation on how to build it.

I have a variation of the solution @LGinC posted and it works.

What doesn't work is using headful mode. Even editing playwright.sh you found errors like
```

System.ComponentModel.Win32Exception (13): Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.Playwright.Transport.Connection..ctor()
   at Microsoft.Playwright.Playwright.CreateAsync()
```

**Comment by h0730303779** [comment]
> The Docker image is necessary, or at least basic documentation on how to build it.
> 
> I have a variation of the solution @LGinC posted and it works.
> 
> What doesn't work is using headful mode. Even editing playwright.sh you found errors like
> 
> ```
> 
> System.ComponentModel.Win32Exception (13): Permission denied
>    at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
>    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
>    at System.Diagnostics.Process.Start()
>    at Microsoft.Playwright.Transport.Connection..ctor()
>    at Microsoft.Playwright.Playwright.CreateAsync()
> ```

your solution ,Can you share it with me?  how  follow-up headful .but  Although I still have the first question

**Comment by pablopioli** [comment]
This Dockerfile works, includes dumb-init

```
FROM mcr.microsoft.com/dotnet/sdk:5.0 as build
WORKDIR /src
COPY ["MyApp.csproj", "MyApp.csproj"]
RUN dotnet restore "MyApp.csproj"
COPY . .
RUN dotnet publish /src/MyApp.csproj -c Release -o /publish
    
FROM mcr.microsoft.com/playwright:focal AS playwright
RUN apt-get update \
    && apt-get install -y wget \
    && wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && apt-get update \
	&& apt-get install dumb-init \
    && apt-get install -y apt-transport-https \
    && apt-get install -y aspnetcore-runtime-5.0 \
    && apt-get remove -y wget
EXPOSE 80
COPY --from=build /publish/ /app/
RUN chown -R pwuser:pwuser /app
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["dotnet", "/app/MyApp.dll"]
```
To run in headfull mode you need another changes, but in the current version you will need to run the container as root

**Comment by pablopioli** [comment]
So, to summarize my opinion, after a whole day of experimentation:

If you run the browser headless you can build an image easily. I don't think a full image is needed, just a little documentation.

If you want to run the browser headful, you're out of luck. Previously it worked with a little tinkering, but not anymore
https://github.com/microsoft/playwright-dotnet/issues/1271

I checked docs and the ones for the Docker image for Java (https://playwright.dev/java/docs/docker/) and the instructions provided are lacking. They omit to mention you need an X server running. 

And if you edit the image to start the X server you will bump into another wall, some permissions are mission. I updated my image to Net 6 and got a more descriptive error

```
System.ComponentModel.Win32Exception (13): An error occurred trying to start process '/app/.playwright/node/linux/playwright.sh' with working directory '/'. Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec) in System.Diagnostics.Process.dll:token 0x600012e+0xcb
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) in System.Diagnostics.Process.dll:token 0x600012d+0x198
   at System.Diagnostics.Process.Start() in System.Diagnostics.Process.dll:token 0x6000105+0xab
   at Microsoft.Playwright.Transport.Connection..ctor() in Microsoft.Playwright.dll:token 0x6000968+0x6f
   at Microsoft.Playwright.Playwright.CreateAsync() in Microsoft.Playwright.dll:token 0x6000959+0xa
```   
Anyway, more permissions are missing. I guess it's because the working directory is set to the root folder

**Comment by h0730303779** [comment]
@pablopioli  thank Your tips for issues/982 .;  I successfully built


mysql dockerfile
```
RUN dotnet tool install --global Microsoft.Playwright.CLI
ENV PATH="${PATH}:/root/.dotnet/tools"
```

Add the above code to solve the problem;  docker Can find  /root/.cache/ms-playwright.....

**Comment by pablopioli** [comment]
So I finally make it to work it on headful mode

Next to the Dockerfile I put a file named playwright.sh. It´s contents are:

```
#!/bin/sh
SCRIPT_PATH="$(cd "$(dirname "$0")" ; pwd -P)"
xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- $SCRIPT_PATH/node $SCRIPT_PATH/../../package/lib/cli/cli.js "$@"
```
Then I inject this file in the image, the second line is the new one

```
COPY --from=build /app .
COPY playwright.sh /app/.playwright/node/linux/playwright.sh
RUN chown -R pwuser:pwuser /app
```

With this recipe and the previous one you can build your own image, in headless and headful modes

**Comment by pablopioli** [comment]
About the size:

A lot comes of the browser binaries:

```
118M    ./webkit-1530/minibrowser-wpe/lib
1.2M    ./webkit-1530/minibrowser-wpe/bin
119M    ./webkit-1530/minibrowser-wpe
102M    ./webkit-1530/minibrowser-gtk/lib
1.5M    ./webkit-1530/minibrowser-gtk/bin
104M    ./webkit-1530/minibrowser-gtk
222M    ./webkit-1530
5.6M    ./ffmpeg-1005
8.0K    ./firefox-1281/firefox/defaults/pref
12K     ./firefox-1281/firefox/defaults
84K     ./firefox-1281/firefox/gmp-clearkey/0.1
88K     ./firefox-1281/firefox/gmp-clearkey
732K    ./firefox-1281/firefox/browser/features
8.0K    ./firefox-1281/firefox/browser/defaults/preferences
12K     ./firefox-1281/firefox/browser/defaults
48K     ./firefox-1281/firefox/browser/chrome/icons/default
52K     ./firefox-1281/firefox/browser/chrome/icons
56K     ./firefox-1281/firefox/browser/chrome
42M     ./firefox-1281/firefox/browser
8.0K    ./firefox-1281/firefox/icons
1.4M    ./firefox-1281/firefox/fonts
207M    ./firefox-1281/firefox
207M    ./firefox-1281
16K     ./chromium-907428/chrome-linux/MEIPreload
5.8M    ./chromium-907428/chrome-linux/ClearKeyCdm/_platform_specific/linux_x64
5.8M    ./chromium-907428/chrome-linux/ClearKeyCdm/_platform_specific
5.8M    ./chromium-907428/chrome-linux/ClearKeyCdm
72K     ./chromium-907428/chrome-linux/resources/inspector_overlay
76K     ./chromium-907428/chrome-linux/resources
57M     ./chromium-907428/chrome-linux/locales
3.8M    ./chromium-907428/chrome-linux/swiftshader
397M    ./chromium-907428/chrome-linux
397M    ./chromium-907428
8.0K    ./.links
831M    .
```

Then there is another 158 MB of Playwright

```
4.0K    ./tmp
416K    ./runtimes/unix/lib/netcoreapp3.0
420K    ./runtimes/unix/lib
424K    ./runtimes/unix
528K    ./runtimes/win/lib/netcoreapp3.0
532K    ./runtimes/win/lib
536K    ./runtimes/win
964K    ./runtimes
25M     ./.playwright/node/win32
29M     ./.playwright/node/win32_x64
46M     ./.playwright/node/mac
47M     ./.playwright/node/linux
145M    ./.playwright/node
216K    ./.playwright/package/lib/server/chromium
24K     ./.playwright/package/lib/server/trace/viewer
20K     ./.playwright/package/lib/server/trace/recorder
8.0K    ./.playwright/package/lib/server/trace/common
56K     ./.playwright/package/lib/server/trace
128K    ./.playwright/package/lib/server/webkit
16K     ./.playwright/package/lib/server/electron
28K     ./.playwright/package/lib/server/android
88K     ./.playwright/package/lib/server/supplements/recorder
24K     ./.playwright/package/lib/server/supplements/har
140K    ./.playwright/package/lib/server/supplements
96K     ./.playwright/package/lib/server/firefox
72K     ./.playwright/package/lib/server/common
64K     ./.playwright/package/lib/server/snapshot
1.2M    ./.playwright/package/lib/server
156K    ./.playwright/package/lib/generated
128K    ./.playwright/package/lib/dispatchers
112K    ./.playwright/package/lib/protocol
36K     ./.playwright/package/lib/test/matchers
64K     ./.playwright/package/lib/test/reporters
312K    ./.playwright/package/lib/test
8.0K    ./.playwright/package/lib/common
260K    ./.playwright/package/lib/client
128K    ./.playwright/package/lib/utils
288K    ./.playwright/package/lib/web/recorder
8.0K    ./.playwright/package/lib/web/traceViewer/ui
344K    ./.playwright/package/lib/web/traceViewer
296K    ./.playwright/package/lib/web/htmlReport
940K    ./.playwright/package/lib/web
44K     ./.playwright/package/lib/third_party/highlightjs/highlightjs/languages
124K    ./.playwright/package/lib/third_party/highlightjs/highlightjs
128K    ./.playwright/package/lib/third_party/highlightjs
212K    ./.playwright/package/lib/third_party
16K     ./.playwright/package/lib/remote
32K     ./.playwright/package/lib/cli
3.5M    ./.playwright/package/lib
24K     ./.playwright/package/node_modules/proper-lockfile/lib
52K     ./.playwright/package/node_modules/proper-lockfile
8.0K    ./.playwright/package/node_modules/concat-map/example
8.0K    ./.playwright/package/node_modules/concat-map/test
40K     ./.playwright/package/node_modules/concat-map
32K     ./.playwright/package/node_modules/fs.realpath
20K     ./.playwright/package/node_modules/commander/typings
132K    ./.playwright/package/node_modules/commander
80K     ./.playwright/package/node_modules/yauzl
52K     ./.playwright/package/node_modules/proxy-from-env
32K     ./.playwright/package/node_modules/extract-zip
20K     ./.playwright/package/node_modules/ms
36K     ./.playwright/package/node_modules/agent-base/dist/src
40K     ./.playwright/package/node_modules/agent-base/dist
20K     ./.playwright/package/node_modules/agent-base/src
76K     ./.playwright/package/node_modules/agent-base
20K     ./.playwright/package/node_modules/path-is-absolute
16K     ./.playwright/package/node_modules/.bin
24K     ./.playwright/package/node_modules/escape-string-regexp
72K     ./.playwright/package/node_modules/glob
32K     ./.playwright/package/node_modules/signal-exit
12K     ./.playwright/package/node_modules/progress/lib
40K     ./.playwright/package/node_modules/progress
20K     ./.playwright/package/node_modules/end-of-stream
64K     ./.playwright/package/node_modules/yazl
36K     ./.playwright/package/node_modules/rimraf
24K     ./.playwright/package/node_modules/brace-expansion
32K     ./.playwright/package/node_modules/debug/src
68K     ./.playwright/package/node_modules/debug
132K    ./.playwright/package/node_modules/ws/lib
168K    ./.playwright/package/node_modules/ws
492K    ./.playwright/package/node_modules/pngjs/coverage/lcov-report
524K    ./.playwright/package/node_modules/pngjs/coverage
124K    ./.playwright/package/node_modules/pngjs/lib
1.2M    ./.playwright/package/node_modules/pngjs
52K     ./.playwright/package/node_modules/graceful-fs
32K     ./.playwright/package/node_modules/pump
44K     ./.playwright/package/node_modules/mime/types
96K     ./.playwright/package/node_modules/mime
20K     ./.playwright/package/node_modules/inflight
16K     ./.playwright/package/node_modules/fd-slicer/test
56K     ./.playwright/package/node_modules/fd-slicer
48K     ./.playwright/package/node_modules/minimatch
48K     ./.playwright/package/node_modules/https-proxy-agent/dist
64K     ./.playwright/package/node_modules/https-proxy-agent
24K     ./.playwright/package/node_modules/inherits
32K     ./.playwright/package/node_modules/get-stream
8.0K    ./.playwright/package/node_modules/balanced-match/.github
28K     ./.playwright/package/node_modules/balanced-match
24K     ./.playwright/package/node_modules/buffer-crc32
68K     ./.playwright/package/node_modules/jpeg-js/lib
108K    ./.playwright/package/node_modules/jpeg-js
20K     ./.playwright/package/node_modules/once
20K     ./.playwright/package/node_modules/@types/yauzl
8.0K    ./.playwright/package/node_modules/@types/node/assert
12K     ./.playwright/package/node_modules/@types/node/stream
20K     ./.playwright/package/node_modules/@types/node/dns
48K     ./.playwright/package/node_modules/@types/node/fs
20K     ./.playwright/package/node_modules/@types/node/ts3.6
8.0K    ./.playwright/package/node_modules/@types/node/timers
1.8M    ./.playwright/package/node_modules/@types/node
1.8M    ./.playwright/package/node_modules/@types
20K     ./.playwright/package/node_modules/wrappy
24K     ./.playwright/package/node_modules/pend
12K     ./.playwright/package/node_modules/retry/example
24K     ./.playwright/package/node_modules/retry/test/integration
32K     ./.playwright/package/node_modules/retry/test
12K     ./.playwright/package/node_modules/retry/lib
100K    ./.playwright/package/node_modules/retry
28K     ./.playwright/package/node_modules/stack-utils
4.8M    ./.playwright/package/node_modules
1.2M    ./.playwright/package/types
1.7M    ./.playwright/package/bin
13M     ./.playwright/package
158M    ./.playwright
171M    .
```

I edited the Dockerfile to avoid unnecesary layers:

```
FROM mcr.microsoft.com/playwright:focal AS playwright
WORKDIR /app
EXPOSE 80
RUN apt-get update \
    && apt-get install -y wget \
    && wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && apt-get update \
	&& apt-get install dumb-init \
    && apt-get install -y apt-transport-https \
    && apt-get install -y aspnetcore-runtime-5.0 \
    && apt-get remove -y wget
RUN chown -R pwuser:pwuser /app
COPY --from=build /app .
COPY playwright.sh /app/.playwright/node/linux/playwright.sh
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["dotnet", "/app/myapp.dll"]
```

and I ended with this layers
```
IMAGE          CREATED              CREATED BY                                      SIZE      COMMENT
05cc3fd8b6cf   About a minute ago   CMD ["dotnet" "/app/myapp.dll"]           0B        buildkit.dockerfile.v0
<missing>      About a minute ago   ENTRYPOINT ["/usr/bin/dumb-init" "--"]          0B        buildkit.dockerfile.v0
<missing>      About a minute ago   COPY playwright.sh /app/.playwright/node/lin…   189B      buildkit.dockerfile.v0
<missing>      About a minute ago   COPY /app . # buildkit                          176MB     buildkit.dockerfile.v0
<missing>      About a minute ago   RUN /bin/sh -c chown -R pwuser:pwuser /app #…   3.12kB    buildkit.dockerfile.v0
<missing>      About a minute ago   RUN /bin/sh -c apt-get update     && apt-get…   102MB     buildkit.dockerfile.v0
<missing>      About a minute ago   EXPOSE map[80/tcp:{}]                           0B        buildkit.dockerfile.v0
<missing>      2 hours ago          WORKDIR /app                                    0B        buildkit.dockerfile.v0
<missing>      2 weeks ago          /bin/sh -c mkdir /ms-playwright &&     mkdir…   1.39GB
<missing>      2 weeks ago          /bin/sh -c #(nop) COPY file:511e93f74e917a93…   1.72MB
<missing>      2 weeks ago          /bin/sh -c #(nop)  ENV PLAYWRIGHT_BROWSERS_P…   0B
<missing>      2 weeks ago          /bin/sh -c apt-get update && apt-get install…   213MB
<missing>      2 weeks ago          /bin/sh -c adduser pwuser                       333kB
<missing>      2 weeks ago          /bin/sh -c apt-get update && apt-get install…   92.7MB
<missing>      2 weeks ago          /bin/sh -c apt-get update && apt-get install…   182MB
<missing>      6 weeks ago          /bin/sh -c #(nop)  CMD ["bash"]                 0B
<missing>      6 weeks ago          /bin/sh -c #(nop) ADD file:524e8d93ad65f08a0…   72.8MB
```
So, to reduce the image size the only viable option is to not bake all browers, only the one needed. But, as this image comes from upstream a custom image would be needed

**Comment by matthewteeter** [comment]
I've spent several days trying all solutions here and listed on other issues but can't get any to work for .net 6. I've tried installing dotnet into the playwright image, and installing playwright into the dotnet image. In either scenario, the error I get when running my .net program which invokes Playwright Nuget lib is "Looks like Playwright Test or Playwright was just installed or updated. Please run the following command to download new browsers: playwright install", even though all 3 browsers have already been downloaded (via the playwright image into /ms-playwright). The Env Var PLAYWRIGHT_BROWSERS_PATH is present and correctly pointing at /ms-playwright. I've tried running as root or as the pwuser user. I am attempting to run in headless mode.

Any official image that would sort this out would be really helpful.

**Comment by NotFazed** [comment]
Hey @matthewteeter - I had the same issue.  Here is a .net 6 version of the dockerfile

FROM mcr.microsoft.com/dotnet/sdk:6.0 as build
WORKDIR /src
COPY ["MyProj.csproj", "MyProj.csproj"]
RUN dotnet restore "MyProj.csproj"
COPY . .
RUN dotnet publish /src/MyProj.csproj -c Release -o /publish
    
FROM mcr.microsoft.com/playwright:focal AS playwright
RUN apt-get update \
    && apt-get install -y wget \
    && wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && apt-get update \
	&& apt-get install dumb-init \
    && apt-get install -y apt-transport-https \
    && apt-get install -y aspnetcore-runtime-6.0 \
    && apt-get remove -y wget
EXPOSE 80
COPY --from=build /publish/ /app/
RUN chown -R pwuser:pwuser /app
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["dotnet", "/app/MyProj.dll"]

**Comment by n3nikita** [comment]
I'm getting this error when trying to set up docker container with Playwright and .NET 6

```
Host system is missing dependencies!

Full list of missing libraries:
    oleacc.dll
    d3d9.dll
    dxgi.dll
    wininet.dll
    usp10.dll
```

**Comment by pablopioli** [comment]
Those are windows dll files. You must be compiling to Windows instead to target Linux

**Comment by LGinC** [comment]
@mxschmitt 
```bash
docker pull mcr.microsoft.com/playwright/dotnet:focal
Trying to pull mcr.microsoft.com/playwright/dotnet:focal...
  manifest unknown: manifest tagged by "focal" is not found
Error: error pulling image "mcr.microsoft.com/playwright/dotnet:focal": unable to pull mcr.microsoft.com/playwright/dotnet:focal: unable to pull image: Error initializing source docker://mcr.microsoft.com/playwright/dotnet:focal: Error reading manifest focal in mcr.microsoft.com/playwright/dotnet: manifest unknown: manifest tagged by "focal" is not found
```

**Comment by mxschmitt** [comment]
For now it's:
`mcr.microsoft.com/playwright/dotnet:next-focal` and in 1.20 it gets focal.

**Comment by viktorilin** [comment]
Hi @mxschmitt,

I was trying to configure C# tests running on GitLab CI and was struggling as I am new in GitLab CI and Docker images.
Accidentally I found this "Feature" discussion, used provided image and everything works fine for me now.
Could you please update the playwright documentation for .Net part so there will be no new issues for other people?

Regards,
Viktor

**Comment by rhyek** [comment]
I noticed the image is not multi-arch like the base playwright image:
![image](https://user-images.githubusercontent.com/702922/167281336-670f31ed-7ac5-4bae-b2f1-d969ae71c858.png)

**Comment by mxschmitt** [comment]
Good catch! Let me add it for the next version.

See here: https://github.com/microsoft/playwright-dotnet/issues/2133

**Comment by JakeStevenson** [comment]
Did you expect this to be changed with v1.22.0?    I still don't see an arm64 version of the playwright/dotnet image.  I'm comparing the list at `https://mcr.microsoft.com/v2/playwright/tags/list` to `https://mcr.microsoft.com/v2/playwright/dotnet/tags/list`, and also looking at the manifests from `docker manifest` as rhyek posted above.

**Comment by mxschmitt** [comment]
Arm is currently blocked by https://github.com/microsoft/playwright-dotnet/issues/2053

**Comment by mxschmitt** [comment]
This should be fixed now and be available under: `playwright.azurecr.io/public/playwright/dotnet:next`.

In version 1.24 then under: `playwright.azurecr.io/public/playwright/dotnet:v1.24` which gets released in 1-2 weeks.
