### ISSUE TITLE
[Question]: Playwright.CreateAsync() Permission denied on Linux

### ISSUE THREAD

**Issue by LGinC** [microsoft/playwright-dotnet#1643]
### Playwright version

1.13.0

### Operating system

Linux

### What browsers are you seeing the problem on?

Chromium

### Other information

.net 6.0 preview 6
ubuntu 20.04.2 LTS (Focal Fossa)

### What happened? / Describe the bug

```csproj
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="5.0.0" />
    <PackageReference Include="Microsoft.Playwright" Version="1.13.0" />
  </ItemGroup>
```

correctly on windows 10,  `Permission denied` on linux.

`dotnet publish` on windows, and copy all dll to linux and `dotnet xx.dll`.    
but it work correctly when `dotnet publish` on linux and `dotnet xx.dll` on linux

### Code snippet to reproduce your bug

```shell
var playwright = await Playwright.CreateAsync();
var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
{
   Headless = true,
   SlowMo = 100,
});
```

### Relevant log output

```shell
Unhandled exception. System.ComponentModel.Win32Exception (13): Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec) in System.Diagnostics.Process.dll:token 0x6000122+0xad
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) in System.Diagnostics.Process.dll:token 0x6000121+0x1aa
   at System.Diagnostics.Process.Start() in System.Diagnostics.Process.dll:token 0x60000fa+0xab
   at Microsoft.Playwright.Transport.Connection..ctor() in Microsoft.Playwright.dll:token 0x60007c5+0x6f
   at Microsoft.Playwright.Playwright.CreateAsync() in Microsoft.Playwright.dll:token 0x60007b6+0xa
```

**Comment by avodovnik** [comment]
This looks like a permission problem - when copying the files manually, it's up to you to make sure the permission on the folder are correct.   Depending on the context you're running from, you should need at least 

```bash
chmod u+rwx .playwright
```

**Comment by LGinC** [comment]
> This looks like a permission problem - when copying the files manually, it's up to you to make sure the permission on the folder are correct. Depending on the context you're running from, you should need to at least run the following command from the folder you're copying _to_:
> 
> ```shell
> chmod u+rwx .playwright
> ```

thx

**Comment by 304NotModified** [comment]
I had the same issue with 

```c#
Microsoft.Playwright.Program.Main(new[] { "install" });
```

error:

> System.ComponentModel.Win32Exception : Permission denied

stack trace for easier to find this issue for others:

version 1.22


```
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.Playwright.Program.Run(String[] args) in /_/src/Playwright/Program.cs:line 66
   at Microsoft.Playwright.Program.Main(String[] args) in /_/src/Playwright/Program.cs:line 36
```

**Comment by 304NotModified** [comment]
FYI,

A one-liner script if the .playwright folder is in some bin folder (e.g. bin/release/net6) and you need a script that works if you're going to .NET 7

bash:
```bash
find . -type d -name ".playwright" -exec chmod -R +x {} \;
```
