### ISSUE TITLE
[Bug]: Setup will not work with .NET 4.8

### ISSUE THREAD

**Issue by Jojoshua** [microsoft/playwright-dotnet#1694]
### Playwright version

1.14

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

Running the program gave this error

Driver not found: C:\Users\user\Source\Repos\PlaywriteTest\.playwright\node\win32_x64\playwright.cmd'

### Code snippet to reproduce your bug

```shell
1. dotnet tool install --global Microsoft.Playwright.CLI
2. Create .NET 4.8 console app with the following code

using Microsoft.Playwright;
using System.Threading.Tasks;

namespace PlaywriteTest
{
    class Program
    {
        static async Task Main(string[] args)
        {
            await Go().ConfigureAwait(false);
        }

        public static async Task Go()
        {
            using (var playwright = await Playwright.CreateAsync())
            {
                var browser = await playwright.Chromium.LaunchAsync();
                var page = await browser.NewPageAsync();
                await page.GotoAsync("https://playwright.dev/dotnet");
                await page.ScreenshotAsync(new PageScreenshotOptions { Path = "screenshot.png" });
                await browser.DisposeAsync();
            }
        }
    }
}

When I tried the same steps except using .NET Core 3.1 everything worked fine.
```

### Relevant log output

```shell
If I try to run playwright install (for the 4.8 project) in the Package Manager Console, I get...

PM> playwright install
playwright : Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=5.0.0.0, 
Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
At line:1 char:1
+ playwright install
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unhandled excep...file specified.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
File name: 'Microsoft.Bcl.AsyncInterfaces, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Microsoft.Playwright.CLI.Program.Main(String[] args) in /_/src/Playwright.CLI/Program.cs:line 75
```

**Comment by atiris** [comment]
Yes, this bothered me too. It looks like some paths in the library are not set up correctly and expect an `.playwright` folder directly in the project directory.
As a workaround you can try to copy: `<solution>\packages\Microsoft.Playwright.1.14.0\.playwright\` directory directly into `<solution>\<project>\` - this, of course, is not a permanent solution.

**Comment by Jojoshua** [comment]
Thanks for the tip @atiris . I tried this and got a different result running the program, Playwright threw Microsoft.Playwright.PlaywrightException: 'Process exited' as soon as it hit `using (var playwright = await Playwright.CreateAsync())` .

**Comment by avodovnik** [comment]
> Thanks for the tip @atiris . I tried this and got a different result running the program, Playwright threw Microsoft.Playwright.PlaywrightException: 'Process exited' as soon as it hit `using (var playwright = await Playwright.CreateAsync())` .

That would usually imply a missing installation... did you run `playwright install`? 

The 4.8 issue where `.playwright` isn't copied correctly is definitely a bug. Working to fix it.

**Comment by atiris** [comment]
yes, of course @avodovnik , i ran this and playwright installed my browsers in:

Playwright build of chromium v907428 downloaded to C:\Users\<name>\AppData\Local\ms-playwright\chromium-907428
Playwright build of ffmpeg v1005 downloaded to C:\Users\<name>\AppData\Local\ms-playwright\ffmpeg-1005
Playwright build of firefox v1281 downloaded to C:\Users\<name>\AppData\Local\ms-playwright\firefox-1281
Playwright build of webkit v1530 downloaded to C:\Users\<name>\AppData\Local\ms-playwright\webkit-1530

Package is installed in c:\Users\<name>\Workspaces\<solution>\packages\Microsoft.Playwright.1.14.0\

CLI is installed in c:\Users\<name>\.nuget\packages\microsoft.playwright\1.14.0

Until the moment I copied the folder `c:\Users\<name>\Workspaces\<solution>\packages\Microsoft.Playwright.1.14.0\.playwright\` to `c:\Users\<name>\Workspaces\<solution>\<project>\` I got the error: The system cannot find the file specified. Now everything is working.

**Comment by Jojoshua** [comment]
> > Thanks for the tip @atiris . I tried this and got a different result running the program, Playwright threw Microsoft.Playwright.PlaywrightException: 'Process exited' as soon as it hit `using (var playwright = await Playwright.CreateAsync())` .
> 
> That would usually imply a missing installation... did you run `playwright install`?
> 
> The 4.8 issue where `.playwright` isn't copied correctly is definitely a bug. Working to fix it.

@avodovnik I did a playwright install (and downloaded chromimum only) and my core 3.1 project worked fine. My understanding is that you only have to run playwright install once, not for every project right? In any regard if I tried to run playwright install under the 4.8 package manager project it throws the error listed in the first post under Relevant log output.

**Comment by avodovnik** [comment]
There are two separate bugs here, actually:

1) Our CLI discovery of the `Microsoft.Playwright.dll` is flawed, because it uses the _first_ dll it finds, which could be a 4.8. That's not actually supported, because it gets loaded into the CLI, which itself needs 3.1. This **could** be resolved, if you also target .net core 3.1 (but not 5.0) and we'll discover it first and it will load correctly. Note, this is a workaround, not a fix. The fix here would be to load the .NET5.0 DLL (which we know can be found in NuGet cache), so I'll see if there's a solution to this, that reverts to that place if the DLL loading fails.

2) The `.playwright` folder missing is a symptom of a different issue, where `build` folder was replaced by `buildTransitive` in the NuGet package that we produce. That folder isn't supported in 4.8. I've now added tests to catch it in the future, and it should also be fixed in the next version. (see #1738).

**Comment by timmkrause** [comment]
I am not sure if this should now be fixed with 1.15.0 for .NET Framework 4.8.

Just wanted to point out that I am still experiencing this issue.

**Comment by aleksandergogoc** [comment]
I am experiencing the same issue with Playwright 1.15.0 in project using .NET Core 3.1. No workarounds are working here or I don't know how to apply them.

**Comment by timmkrause** [comment]
**Local workaround:** You can follow the [First test guide](https://playwright.dev/dotnet/docs/intro#first-test), the latest browsers will then be installed. Other projects should then have the same Playwright package version as the one from the sample/init project.

**Agent workaround (only for stateful agents...):** Same as above (and delete project folder afterwards), but before `playwright install` override the default behavior/path where browser are being installed to by setting the `PLAYWRIGHT_BROWSERS_PATH` environment variable, this is taken from [here](https://playwright.dev/dotnet/docs/browsers#managing-browser-binaries) to a location where the browsers should be installed, `playwright install` will consider this variable. This variable should also be set when Playwright tests are being executed as browsers are then as well pulled from the specified location.

**Comment by pavelfeldman** [comment]
Things should work on latest Playwright.

**Comment by timmkrause** [comment]
It doesn't work for me.

**Comment by timmkrause** [comment]
Woohoo, it's working now with `Microsoft.Playwright(.NUnit)` 1.15.3 **AND** the latest global tool `Microsoft.Playwright.CLI` 1.2.0.

Thanks!
