### ISSUE TITLE
[Bug]: evaluate deserialize array error

### ISSUE THREAD

**Issue by hi-xiaoxin** [microsoft/playwright-dotnet#1706]
### Playwright version

1.14.0

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

```
await page.EvaluateAsync("()=>{ return { a:[1,2]} }") 
//success , result: ValueKind = Object : "{"a":[1,2]}"
```

```
await page.EvaluateAsync("()=>{ return [1,2]}")  
//error message: Value cannot be null
//someitmes return  ValueKind: 'result.Value.ValueKind' threw an exception of type 'System.ObjectDisposedException'
```

StackTrace:

   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at Microsoft.Playwright.Transport.Converters.EvaluateArgumentValueConverter`1.GetNewConverter(Type type)
   at Microsoft.Playwright.Transport.Converters.EvaluateArgumentValueConverter`1.ParseEvaluateResult(JsonElement result, Type t, JsonSerializerOptions options)
   at Microsoft.Playwright.Transport.Converters.EvaluateArgumentValueConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at Microsoft.Playwright.Transport.Converters.EvaluateArgumentValueConverter`1.ParseEvaluateResult(JsonElement result, Type t, JsonSerializerOptions options)
   at Microsoft.Playwright.Transport.Converters.EvaluateArgumentValueConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Microsoft.Playwright.Helpers.JsonExtensions.ToObject[T](JsonElement element, JsonSerializerOptions options)
   at Microsoft.Playwright.Core.ScriptsHelper.ParseEvaluateResult[T](Nullable`1 result)
   at Microsoft.Playwright.Core.Frame.<EvaluateAsync>d__81`1.MoveNext()

### Code snippet to reproduce your bug

```shell
using System.Threading.Tasks;
using Microsoft.Playwright;

class Program
{
    public static async Task Main()
    {
        using var playwright = await Playwright.CreateAsync();
        await using var browser = await playwright.Chromium.LaunchAsync();
        var page = await browser.NewPageAsync();
        var result = await page.EvaluateAsync("()=> [1,2]");
        Console.WirteLine(result );
    }
}
```

**Comment by hi-xiaoxin** [comment]
may i custom json converter at startup ?

**Comment by avodovnik** [comment]
In this particular case, you should tell it you're expecting an array so we know what to deserialize, i.e.:

```csharp
var result = await page.EvaluateAsync<int[]>("()=>{ return [1,2]}");
```

**Comment by hi-xiaoxin** [comment]
@avodovnik 

thank you for your reply.

but if return a array of object, it's will throw exception

`await page.EvaluateAsync<JsonElement[]>("()=> [{a:1,b:2},{a:1,b:2}]")`

**error message:**

The JSON value could not be converted to System.Text.Json.JsonElement[]. Path: $ | LineNumber: 0 | BytePositionInLine: 1. Path: $ | LineNumber: 0 | BytePositionInLine: 105. Path: $ | LineNumber: 0 | BytePositionInLine: 121.

i think the function 'EvaluateAsync' should return a jsonvalue/jsonobject /jsonarray and it can be deserialized

thanks

**Comment by hi-xiaoxin** [comment]
i tried dynamic generic parameter, it's worked

`await page.EvaluateAsync<dynamic>("()=> [{a:1,b:2},{a:1,b:2}]")`

if support custom json serialize, it will be perfect

**Comment by avodovnik** [comment]
I think there's a bug in what we're returning, I'll do some more investigating. Thanks for bringing this up.
