### ISSUE TITLE
[Bug]: Calling Locator() on another ILocator causes Connection Closed error.

### ISSUE THREAD

**Issue by corygehr** [microsoft/playwright-dotnet#1745]
### Playwright version

1.14.0

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium (default installed by playwright).

### Other information

.NET 5

### What happened? / Describe the bug

When calling `Locator()` on an existing `ILocator` object, the method returns but subsequent calls on the returned object throw a `PlaywrightException`:

```
Connection closed (System.Threading.ThreadAbortException: System error.
   at System.Diagnostics.Debugger.CustomNotification(ICustomDebuggerNotification data)
   at System.Diagnostics.Debugger.NotifyOfCrossThreadDependencySlow()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.GetStateMachineBox[TStateMachine](TStateMachine& stateMachine, Task`1& taskField)
   at Microsoft.Playwright.Transport.StdIOTransport.SendAsync(String message))
```
I encountered the same issue in Playwright 1.13.x with `IElementHandle` objects. Somehow, it appears the pipe between the .NET wrapper the node driver is getting closed when attempting to do nested Locator calls.

In my use case, I want to identify child elements of particular parent HTML nodes. At one point, I managed to get the following exception, but no idea what I did differently to get this to fire:

```
Unknown engine "_nth" while parsing selector xpath=//form >> _nth=$0 >> xpath=/input

at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Playwright.Transport.Connection.<SendMessageToServerAsync>d__19`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Playwright.Core.Frame.<EvalOnSelectorAllAsync>d__86`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

### Code snippet to reproduce your bug

**This is a simplified example. In my project, I have a wrapper class for the `ILocator` and `IPage` objects but I have no reason to believe the garbage collector is disposing my browser.**

```shell
// Simplified example, assumes one form exists on the page.
var result = new List<Locator>();

// Assume 'IPage' is your existing IPage.
var parent = IPage.Locator("xpath=//form");

if (parent != null && await parent.CountAsync() > 0)
{
    var children = parent.Nth(0).Locator("xpath=/input");

    if (children != null)
    {
        // Exception occurs here.
        var elementCount = await children.CountAsync();

        for (var i = 0; i < elementCount; i++)
        {
            result.Add(children.Nth(i));
        }
    }
}
```

### Relevant log output

```shell
Connection closed (System.Threading.ThreadAbortException: System error.
   at System.Diagnostics.Debugger.CustomNotification(ICustomDebuggerNotification data)
   at System.Diagnostics.Debugger.NotifyOfCrossThreadDependencySlow()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.GetStateMachineBox[TStateMachine](TStateMachine& stateMachine, Task`1& taskField)
   at Microsoft.Playwright.Transport.StdIOTransport.SendAsync(String message))

at Microsoft.Playwright.Transport.Connection.<SendMessageToServerAsync>d__19`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Playwright.Core.Frame.<EvalOnSelectorAllAsync>d__86`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

**Comment by dayadam** [comment]
I got the two above errors, as well as what looks like an empty thread waiting for a computation to execute or something 

https://drive.google.com/file/d/1lp_ChFEENC-5-8cl4-Up_EpV4i0sWOjS/view?usp=sharing

Maybe an async problem in node?

**Comment by dayadam** [comment]
@pavelfeldman Thank you so much for resolving the parsing issue, but it looks like that PR doesn't fix our connection dropping issue!

**Comment by pavelfeldman** [comment]
Is there a repro we could use?

**Comment by dayadam** [comment]
@pavelfeldman Sure! https://github.com/dayadam/PlaywrightConnectionRepro4
