### ISSUE TITLE
[BUG] Error when produce single file

### ISSUE THREAD

**Issue by zzquilt** [microsoft/playwright-dotnet#1952]
When I publish the application, check the produce single file, it will run error.
- Playwright Version: 1.17.3
- Operating System: Windows
- .NET version: .Net6
- Browser: All
- Extra: Console application

System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at System.IO.FileInfo..ctor(String originalPath, String fullPath, String fileName, Boolean isNormalized)
   at System.IO.FileInfo..ctor(String fileName)
   at Microsoft.Playwright.Helpers.Paths.GetExecutablePath()
   at Microsoft.Playwright.Transport.StdIOTransport.GetProcess()
   at Microsoft.Playwright.Transport.StdIOTransport..ctor()
   at Microsoft.Playwright.Playwright.CreateAsync()
   at BrowserKeep.BrowserKeepService.Keep()

Sorry for my poor English.

**Comment by bugproof** [comment]
This is still broken

![image](https://user-images.githubusercontent.com/3116731/182633014-ccdca4d5-b003-4227-8d2d-898f952cc9cb.png)

**Comment by mxschmitt** [comment]
> This is still broken
> 
> ![image](https://user-images.githubusercontent.com/3116731/182633014-ccdca4d5-b003-4227-8d2d-898f952cc9cb.png)
> 

Please file a separate issue with a repro, thanks.
