### ISSUE TITLE
[Question]: Proper way to dispose of playwright when used in a BackgroundService

### ISSUE THREAD

**Issue by rhyek** [microsoft/playwright-dotnet#2021]
### Your question

I have what is essentially something like this:
```cs
public class BankMonitorService : BackgroundService
{
  private readonly ILogger<BancoIndustrialMonitorService> _logger;

  public BankMonitorService(ILogger<BankMonitorService> logger)
  {
    _logger = logger;
  }
  
  protected override async Task ExecuteAsync(CancellationToken stoppingToken)
  {
    await Monitor(stoppingToken); // error at line 40 here
  }

  private async Task Monitor(CancellationToken stoppingToken)
  {
    _logger.LogInformation("Starting...");
    using var playwright = await Playwright.CreateAsync();
    await using var browser =
      await playwright.Chromium.LaunchAsync(new() {
        Headless = true
      });
  
    while (!stoppingToken.IsCancellationRequested) {
      // ...
    }
  
    _logger.LogInformation("Stopped"); // error at line 96 here
  }
}

```
I run the project from within Rider and when I hit stop I get the following error:
```bash
crit: Microsoft.Extensions.Hosting.Internal.Host[10]
      The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
      Microsoft.Playwright.PlaywrightException: Process exited
         at Microsoft.Playwright.Transport.Connection.SendMessageToServerAsync[T](String guid, String method, Object args)
         at Microsoft.Playwright.Core.Browser.CloseAsync()
         at Microsoft.Playwright.Core.Browser.DisposeAsync()
         at Application.BIMonitor.Services.BankMonitorService.Monitor(CancellationToken stoppingToken) in /Users/.../BankMonitorService.cs:line 96
         at Application.BIMonitor.Services.BankMonitorService.ExecuteAsync(CancellationToken stoppingToken) in /Users/.../BankMonitorService.cs:line 40
         at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
```

So I'm wondering if this is expected or if there might be something I can do differently, thanks.

**Comment by mxschmitt** [comment]
Which operating system and architecture are you using? Could you try setting `DEBUG=pw:browser,pw:api` environment variables?

**Comment by rhyek** [comment]
I'm on MacOS Monterey on an x64 intel chip.

Output with those variables:
```bash
2022-02-26T01:12:43.228Z pw:api   navigations have finished
2022-02-26T01:12:43.510Z pw:api   "domcontentloaded" event fired
2022-02-26T01:12:43.528Z pw:api   "load" event fired
2022-02-26T01:12:44.098Z pw:api   "networkidle" event fired
2022-02-26T01:12:44.165Z pw:api   "DOMContentLoaded" event fired
2022-02-26T01:12:44.170Z pw:api   "Load" event fired
2022-02-26T01:12:44.174Z pw:api waiting for selector "text="Electron"" to be visible
2022-02-26T01:12:44.191Z pw:api   selector resolved to 2 elements. Proceeding with the first one.
2022-02-26T01:12:44.194Z pw:api   selector resolved to visible <td class="text-left">Electron</td>
^C2022-02-26T01:12:45.009Z pw:browser [pid=53549] <gracefully close start>
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
info: FakeSite.Application.YnabController.Services.YnabControllerService[0]
      good bye
info: FakeSite.Application.BIMonitor.Services.FakeSiteService[0]
      Stopped
2022-02-26T01:12:45.045Z pw:browser [pid=53549] <process did exit: exitCode=0, signal=null>
2022-02-26T01:12:45.045Z pw:browser [pid=53549] starting temporary directories cleanup
2022-02-26T01:12:45.049Z pw:browser [pid=53549] finished temporary directories cleanup
2022-02-26T01:12:45.049Z pw:browser [pid=53549] <gracefully close end>

fail: Microsoft.Extensions.Hosting.Internal.Host[9]
      BackgroundService failed
      Microsoft.Playwright.PlaywrightException: Process exited
         at Microsoft.Playwright.Transport.Connection.SendMessageToServerAsync[T](String guid, String method, Object args)
         at Microsoft.Playwright.Core.Browser.CloseAsync()
         at Microsoft.Playwright.Core.Browser.DisposeAsync()
         at FakeSite.Application.BIMonitor.Services.FakeSiteService.Monitor(CancellationToken stoppingToken) in ../fake-site-monitor-dotnetcore/src/FakeSite/Core/BIMonitor/Services/FakeSiteService.cs:line 111
         at FakeSite.Application.BIMonitor.Services.FakeSiteService.ExecuteAsync(CancellationToken stoppingToken) in ../fake-site-monitor-dotnetcore/src/FakeSite/Core/BIMonitor/Services/FakeSiteService.cs:line 54
         at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
crit: Microsoft.Extensions.Hosting.Internal.Host[10]
      The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
      Microsoft.Playwright.PlaywrightException: Process exited
         at Microsoft.Playwright.Transport.Connection.SendMessageToServerAsync[T](String guid, String method, Object args)
         at Microsoft.Playwright.Core.Browser.CloseAsync()
         at Microsoft.Playwright.Core.Browser.DisposeAsync()
         at FakeSite.Application.BIMonitor.Services.FakeSiteService.Monitor(CancellationToken stoppingToken) in ../fake-site-monitor-dotnetcore/src/FakeSite/Core/BIMonitor/Services/FakeSiteService.cs:line 111
         at FakeSite.Application.BIMonitor.Services.FakeSiteService.ExecuteAsync(CancellationToken stoppingToken) in ../fake-site-monitor-dotnetcore/src/FakeSite/Core/BIMonitor/Services/FakeSiteService.cs:line 54
         at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)

Process finished with exit code 0.
```

**Comment by mxschmitt** [comment]
Seems like the browser is already disposing because of the `await using`. So you either need to do it in the same function or don't use `await using`.
