### ISSUE TITLE
[BUG] LaunchPersistentContextAsync timeout with Firefox

### ISSUE THREAD

**Issue by ankyo** [microsoft/playwright-dotnet#2077]
**Context:**
- Playwright Version: 1.20.1
- Operating System: Windows11
- .NET version: .NET6 and .NetCore3.1
- Browser: Firefox
- Extra: Firefox was opened but connection timeout

**Code Snippet**
```cs
IBrowserContext? context = null;

try
{
  context = await playwright.Firefox.LaunchPersistentContextAsync(userDataDir, new BrowserTypeLaunchPersistentContextOptions
  {
    Headless = false,
    SlowMo = 10,
    ExecutablePath = @"D:\vendor\firefox-97.0.1\firefox.exe",
  });
}
catch (Exception ex)
{
  Console.WriteLine(ex.ToString());
}

if (context != null)
{
  var page = await context.NewPageAsync();
  await page.GotoAsync("https://playwright.dev");
  Console.WriteLine("Version: {0}", context.Browser?.Version);
}
else
{
  Console.WriteLine("context is null");
}
```

**Describe the bug**

The code opens Firefox, but getting the IBrowserContext timedout.

**Output**

```bash
Hello, World!
playwright.Firefox.LaunchPersistentContextAsync
System.TimeoutException: Timeout 30000ms exceeded.
=========================== logs ===========================
<launching> D:\vendor\firefox-97.0.1\firefox.exe -no-remote -wait-for-browser -foreground -profile D:\ConsoleApp1\bin\Debug\netcoreapp3.1\firefox-data -juggler-pipe about:blank
<launched> pid=21536
============================================================
   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](String guid, String method, Object args) in /_/src/Playwright/Transport/Connection.cs:line 161
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal)
   at Microsoft.Playwright.Core.BrowserType.LaunchPersistentContextAsync(String userDataDir, BrowserTypeLaunchPersistentContextOptions options) in /_/src/Playwright/Core/BrowserType.cs:line 87
   at ConsoleApp1.PlaywrightTest.LaunchFirefoxAsync() in D:\ConsoleApp1\PlaywrightTest.cs:line 220
context is null
```

**Comment by mxschmitt** [comment]
You can't swap the Firefox executable with a custom one. Since Firefox and WebKit are modified.

Also if it only works the first time with the persistent profile on Firefox, you might run into https://github.com/microsoft/playwright/issues/12632.

**Comment by ankyo** [comment]
> You can't swap the Firefox executable with a custom one. Since Firefox and WebKit are modified.
> 
> Also if it only works the first time with the persistent profile on Firefox, you might run into [microsoft/playwright#12632](https://github.com/microsoft/playwright/issues/12632).

fixed it, thanks a lot
