### ISSUE TITLE
[Question]: Host system is missing a few dependencies to run browsers.

### ISSUE THREAD

**Issue by bloodgang94** [microsoft/playwright-dotnet#2081]
### Your question

Hey! I'm new to creating docker files and could you tell me what's wrong with it?
Playwright 1.20.2, Xunit , SpecFlow
```
FROM mcr.microsoft.com/playwright/dotnet:v1.20.2-focal AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443
#Install powershell to playwright scripts
RUN apt-get update -yq \
    && apt-get install wget -yq \
    && wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && apt-get update -yq \
    && apt-get install powershell -yq


FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Playwright/Playwright.csproj", "Playwright/"]
RUN dotnet restore "Playwright/Playwright.csproj"
COPY . .
WORKDIR "/src/Playwright"
RUN dotnet build "Playwright.csproj" -c Release -o /app/build
RUN dotnet tool update --global PowerShell
RUN pwsh /app/build/playwright.ps1 install chromium
RUN pwsh /app/build/playwright.ps1 install-deps
RUN dotnet test
```

Full Output 

```
#1 [internal] load build definition from Dockerfile
#1 sha256:2338139d0ee012c0cad7e8e5d2ff3d40fab496081b48a5dbe192e6aafd25c051
#1 transferring dockerfile: 1.44kB 0.0s done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 sha256:b335f8294da7c2193a407b0ae1ce80b92d34d62df43785157c2d564cf55486ea
#2 transferring context: 35B done
#2 DONE 0.0s

#3 [internal] load metadata for mcr.microsoft.com/dotnet/sdk:6.0
#3 sha256:9eb4f6c3944cfcbfe18b9f1a753c769fc35341309a8d4a21f8937f47e94c712b
#3 DONE 0.0s

#4 [internal] load metadata for mcr.microsoft.com/playwright/dotnet:v1.20.2-focal
#4 sha256:8d4d75c93888f2e7a069de4e052bb83793daa6b7eca81a66d27a0ffb5776e756
#4 DONE 0.0s

#9 [build  1/11] FROM mcr.microsoft.com/dotnet/sdk:6.0
#9 sha256:7ecb41e81f15ad01ec9dfe74e314966dca2b7e75c8209ba0f5971e2896aeacb1
#9 DONE 0.0s

#5 [base 1/3] FROM mcr.microsoft.com/playwright/dotnet:v1.20.2-focal
#5 sha256:03cb98381a2bd738bcc860e05a3aacf33451c808290bf3ca27a5834be3a8d914
#5 DONE 0.0s

#11 [internal] load build context
#11 sha256:bdf66935426edbd354b5305519d15c575ab31039362a19b38940e1878401928f
#11 transferring context: 2.28kB 0.0s done
#11 DONE 0.1s

#16 [build  7/11] RUN dotnet build "Playwright.csproj" -c Release -o /app/build
#16 sha256:a270e451a2e773f005a08beffb3b01eb3b879150fcb58d155f77891f31cbb443
#16 CACHED

#14 [build  5/11] COPY . .
#14 sha256:ad4ec592a5b91824cd44a17d5dfc020576dcf93284e2dbda31ad709f9845808f
#14 CACHED

#15 [build  6/11] WORKDIR /src/Playwright
#15 sha256:221eb4f4755a26ccf1bba27d325b20502539aa231b1d18b0704c8c6b787aa799
#15 CACHED

#12 [build  3/11] COPY [Playwright/Playwright.csproj, Playwright/]
#12 sha256:05d05e9581f341c66acbacaa1c5e20c013797a7d73dced90ea13de157fc631dc
#12 CACHED

#13 [build  4/11] RUN dotnet restore "Playwright/Playwright.csproj"
#13 sha256:08611879a26341b41fdb57632ee906b1c5659afff932071db084d6f1ff8ddadd
#13 CACHED

#17 [build  8/11] RUN dotnet tool update --global PowerShell
#17 sha256:69aa7cb7e27318ba3097000c1bbf3eeaf7a2985127ff0ca3e2273115eb98f621
#17 CACHED

#10 [build  2/11] WORKDIR /src
#10 sha256:5ab03db9c756d494d26f6f951935e98641cd0ac874530e7c026c9e03c0da1894
#10 CACHED

#18 [build  9/11] RUN pwsh /app/build/playwright.ps1 install chromium
#18 sha256:82a00200a7ec40a0b1604c2d93fd2fbb8b398bc925b12ce597829d73c17d6f43
#18 CACHED

#19 [build 10/11] RUN pwsh /app/build/playwright.ps1 install-deps
#19 sha256:dccdd58c2cb68aa0a949ef04a0b24d8c35361bbbb2627c04a2bb5cf0d50c53cd
#19 1.366 Installing Ubuntu dependencies...
#19 1.545 Get:1 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
#19 1.625 Get:2 http://deb.debian.org/debian bullseye InRelease [116 kB]
#19 1.697 Get:3 http://deb.debian.org/debian bullseye-updates InRelease [39.4 kB]
#19 1.778 Get:4 http://security.debian.org/debian-security bullseye-security/main amd64 Packages [123 kB]
#19 1.921 Get:5 http://deb.debian.org/debian bullseye/main amd64 Packages [8182 kB]
#19 2.444 Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [2596 B]
#19 3.659 Fetched 8507 kB in 2s (3756 kB/s)
#19 4.229 Reading package lists...
#19 4.677 Reading package lists...
#19 4.819 Building dependency tree...
#19 4.819 Reading state information...
#19 4.835 Package ttf-ubuntu-font-family is not available, but is referred to by another package.
#19 4.835 This may mean that the package is missing, has been obsoleted, or
#19 4.835 is only available from another source
#19 4.835
#19 4.835 Package libjpeg-turbo8 is not available, but is referred to by another package.
#19 4.835 This may mean that the package is missing, has been obsoleted, or
#19 4.835 is only available from another source
#19 4.835
#19 4.899 E: Package 'ttf-ubuntu-font-family' has no installation candidate
#19 4.899 E: Unable to locate package libenchant1c2a
#19 4.899 E: Unable to locate package libicu66
#19 4.899 E: Package 'libjpeg-turbo8' has no installation candidate
#19 DONE 5.0s

#20 [build 11/11] RUN dotnet test
#20 sha256:47d7c6b6d2845172d9375039063c0361293bd62ba6ef6ecb49ca59a235572d2b
#20 1.114   Determining projects to restore...
#20 1.407   All projects are up-to-date for restore.
#20 1.508   SpecFlowFeatureFiles: Features/Feature1.feature
#20 1.558 -> Using default config
#20 1.724   SpecFlowGeneratedFiles: Features/Feature1.feature.cs
#20 5.340   Playwright -> /src/Playwright/bin/Debug/net6.0/Playwright.dll
#20 5.380 Test run for /src/Playwright/bin/Debug/net6.0/Playwright.dll (.NETCoreApp,Version=v6.0)
#20 5.579 Microsoft (R) Test Execution Command Line Tool Version 17.1.0
#20 5.580 Copyright (c) Microsoft Corporation.  All rights reserved.
#20 5.580
#20 5.763 Starting test execution, please wait...
#20 5.816 A total of 1 test files matched the specified pattern.
#20 7.788 -> Loading plugin /src/Playwright/bin/Debug/net6.0/TechTalk.SpecFlow.xUnit.SpecFlowPlugin.dll
#20 7.793 -> Loading plugin /src/Playwright/bin/Debug/net6.0/Playwright.dll
#20 7.827 -> Using default config
#20 9.031 [xUnit.net 00:00:02.47]     [scenario name] [FAIL]
#20 9.123   Failed [scenario name] [1 s]
#20 9.123   Error Message:
#20 9.123    Microsoft.Playwright.PlaywrightException :
#20 9.123 ╔════════════════════════════════════════════════════════════╗
#20 9.123 ║ Host system is missing a few dependencies to run browsers. ║
#20 9.123 ║ Please install them with the following command:            ║
#20 9.123 ║                                                            ║
#20 9.123 ║     pwsh bin\Debug\netX\playwright.ps1 install-deps        ║
#20 9.123 ║                                                            ║
#20 9.123 ║ <3 Playwright Team                                         ║
#20 9.123 ╚════════════════════════════════════════════════════════════╝
#20 9.123   Stack Trace:
#20 9.123      at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.FireEvents(HookType hookType)
#20 9.123    at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.FireScenarioEvents(HookType bindingEvent)
#20 9.123    at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnScenarioStart()
#20 9.123    at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
#20 9.123    at TechTalk.SpecFlow.TestRunner.CollectScenarioErrors()
#20 9.123    at Playwright.Features.Feature1Feature.ScenarioCleanup()
#20 9.123    at Playwright.Features.Feature1Feature.ScenarioName() in /src/Playwright/Features/Feature1.feature:line 9
#20 9.123   Standard Output Messages:
#20 9.123  Given [context]
#20 9.123  -> skipped because of previous errors
#20 9.123  When [action]
#20 9.123  -> skipped because of previous errors
#20 9.123  Then [outcome]
#20 9.123  -> skipped because of previous errors
#20 9.123
#20 9.123
#20 9.132
#20 9.139 Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: < 1 ms - /src/Playwright/bin/Debug/net6.0/Playwright.dll (net6.0)
#20 ERROR: executor failed running [/bin/sh -c dotnet test]: exit code: 1
```

When I run docker build I get an error:
║ Host system is missing a few dependencies to run browsers. ║
#20 9.123 ║ Please install them with the following command:            ║
#20 9.123 ║                                                            ║
#20 9.123 ║     pwsh bin\Debug\netX\playwright.ps1 install-deps        ║
#20 9.123 ║                                                            ║
#20 9.123 ║ <3 Playwright Team

**Comment by rwoll** [comment]
We currently don't have an officially supported Playwright .NET Docker container.

The error your getting prompts you to run a command to satisfy the deps:

```
 Please install them with the following command:            
                                                     
   pwsh bin\Debug\netX\playwright.ps1 install-deps 
```

so if you add that command (prefixed with the `RUN` docker keyword):

```
RUN pwsh bin\Debug\netX\playwright.ps1 install-deps 
```

in your dockerfile right after:

```
FROM mcr.microsoft.com/dotnet/sdk:6.0
```

it should grab the deps.

Does that work for you?

**Comment by rwoll** [comment]
@bloodgang94 I've hidden my previous comment, as it contained incorrect information. Sorry about that!

I've put together an (**unofficial**) self-contained working example for you to try out and base your work off of: https://github.com/rwoll/playwright-dotnet-example. The README contains instructions for building and running via Docker. Be sure to also read the comments in the Dockerfile as it has some important notes!

The snippet you pasted in your original https://github.com/microsoft/playwright-dotnet/issues/2081#issue-1184965403 does not work because you're using a 2-stage build (indicated by the two `FROM` statements). The image you go to run in the end (`FROM mcr.microsoft.com/dotnet/sdk:6.0`) is Debian based, which **not** currently supported by Playwright.

Docker has lots of surface area and optimizations for writing Dockerfiles; I've created a minimal example, but it's not necessarily the most optimal, but hopeful it works for you to get you started!

Let us know how it goes! 🎉 

(NB: We do not currently publish .NET for M1 macOS—yet.)

**Comment by bloodgang94** [comment]
> @bloodgang94 I've hidden my previous comment, as it contained incorrect information. Sorry about that!
> 
> I've put together an (**unofficial**) self-contained working example for you to try out and base your work off of: https://github.com/rwoll/playwright-dotnet-example. The README contains instructions for building and running via Docker. Be sure to also read the comments in the Dockerfile as it has some important notes!
> 
> The snippet you pasted in your original [#2081 (comment)](https://github.com/microsoft/playwright-dotnet/issues/2081#issue-1184965403) does not work because you're using a 2-stage build (indicated by the two `FROM` statements). The image you go to run in the end (`FROM mcr.microsoft.com/dotnet/sdk:6.0`) is Debian based, which **not** currently supported by Playwright.
> 
> Docker has lots of surface area and optimizations for writing Dockerfiles; I've created a minimal example, but it's not necessarily the most optimal, but hopeful it works for you to get you started!
> 
> Let us know how it goes! 🎉
> 
> (NB: We do not currently publish .NET for M1 macOS—yet.)

Thank you very much! Based on your example, I was able to create a dockerfile.
