### ISSUE TITLE
[Question]:  System.AggregateException : One or more errors occurred. (Browser closed.) when run in docker

### ISSUE THREAD

**Issue by bloodgang94** [microsoft/playwright-dotnet#2085]
### Your question

Hello. I set up a docker file.
Xnunit, SpecFlow, Playwright
mcr.microsoft.com/playwright/dotnet:v1.20.2-focal
Local tests pass without errors.
When run in docker
```
 Error Message:
   System.AggregateException : One or more errors occurred. (Browser closed.
==================== Browser output: ====================
<launching> /ms-playwright/chromium-978106/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-5yZJip --remote-debugging-pipe --no-startup-window
<launched> pid=394
[pid=394][err] [394:394:0331/122107.796475:ERROR:ozone_platform_x11.cc(247)] Missing X server or $DISPLAY
[pid=394][err] [394:394:0331/122107.796570:ERROR:env.cc(225)] The platform failed to initialize.  Exiting.
=========================== logs ===========================
<launching> /ms-playwright/chromium-978106/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-5yZJip --remote-debugging-pipe --no-startup-window
<launched> pid=394
[pid=394][err] [394:394:0331/122107.796475:ERROR:ozone_platform_x11.cc(247)] Missing X server or $DISPLAY
[pid=394][err] [394:394:0331/122107.796570:ERROR:env.cc(225)] The platform failed to initialize.  Exiting.
============================================================) (Object reference not set to an instance of an object.)
---- Microsoft.Playwright.PlaywrightException : Browser closed.
==================== Browser output: ====================
<launching> /ms-playwright/chromium-978106/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-5yZJip --remote-debugging-pipe --no-startup-window
<launched> pid=394
[pid=394][err] [394:394:0331/122107.796475:ERROR:ozone_platform_x11.cc(247)] Missing X server or $DISPLAY
[pid=394][err] [394:394:0331/122107.796570:ERROR:env.cc(225)] The platform failed to initialize.  Exiting.
=========================== logs ===========================
<launching> /ms-playwright/chromium-978106/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-5yZJip --remote-debugging-pipe --no-startup-window
<launched> pid=394
[pid=394][err] [394:394:0331/122107.796475:ERROR:ozone_platform_x11.cc(247)] Missing X server or $DISPLAY
[pid=394][err] [394:394:0331/122107.796570:ERROR:env.cc(225)] The platform failed to initialize.  Exiting.
============================================================
---- System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace:

----- Inner Stack Trace #1 (Microsoft.Playwright.PlaywrightException) -----
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.FireEvents(HookType hookType)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.FireScenarioEvents(HookType bindingEvent)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnScenarioStart()
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at TechTalk.SpecFlow.TestRunner.CollectScenarioErrors()
   at SellPlusTest.Features.CheckingAuthorizationInYourPersonalAccountFeature.ScenarioCleanup()
   at SellPlusTest.Features.CheckingAuthorizationInYourPersonalAccountFeature.UserSuccessAuhorization(String role, String title, String[] exampleTags) in /src/SellPlusTest/Features/CheckAuthorization.feature:line 9
----- Inner Stack Trace #2 (System.NullReferenceException) -----
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.FireEvents(HookType hookType)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.FireScenarioEvents(HookType bindingEvent)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnScenarioEnd()
   at TechTalk.SpecFlow.TestRunner.OnScenarioEnd()
   at SellPlusTest.Features.CheckingAuthorizationInYourPersonalAccountFeature.TestTearDown()
   at SellPlusTest.Features.CheckingAuthorizationInYourPersonalAccountFeature.System.IDisposable.Dispose()
   at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in C:\Dev\xunit\xunit\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs:line 79
```

What am I missing?

**Comment by mxschmitt** [comment]
You need to run it with `Headless: false` or use `xvfb-run`. The first is a more performant solution.

**Comment by bloodgang94** [comment]
@mxschmitt  The error disappeared when adding the launch via CMD xvfb-run --auto-servernum dotnet test
Why doesn't this work via BrowserTypeLaunchOptions Headless: false ?

**Comment by mxschmitt** [comment]
Because it requires a real display or a virtual display server (what xvfb-run does). Usually we don't recommend it, since it requires more CPU/memory.
