### ISSUE TITLE
[BUG] Timeout on ScreenshotAsync

### ISSUE THREAD

**Issue by szamacz** [microsoft/playwright-dotnet#2115]
**Context:**
- Playwright Version:1.20.2
- Operating System: Linux
- .NET version: 6.0.202
- Browser: Chrome
- Extra: Headless browser,

**Code Snippet**

```cs
 await page.ScreenshotAsync(new PageScreenshotOptions()
                {
                    Path = $"{_testResultsDir}/screen_shot.jpg",
                    FullPage = true,
                });
```

**Describe the bug**

I observed that from time to time (at least once per 100 test runs) playwright cannot take screenshots and throws a timeout exception. 
```
Setup failed for test fixture MyTests
System.TimeoutException : Timeout 30000ms exceeded.
StackTrace:    at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](String guid, String method, Object args) in /_/src/Playwright/Transport/Connection.cs:line 161
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 487
   at Microsoft.Playwright.Transport.Channels.PageChannel.ScreenshotAsync(String path, Nullable`1 fullPage, Clip clip, Nullable`1 omitBackground, Nullable`1 type, Nullable`1 quality, IEnumerable`1 mask, Nullable`1 timeout) in /_/src/Playwright/Transport/Channels/PageChannel.cs:line 414
   at Microsoft.Playwright.Core.Page.ScreenshotAsync(PageScreenshotOptions options) in /_/src/Playwright/Core/Page.cs:line 591
   at Pyra.Availability.Ui.Tests.Tests.UI.TestsSetup.OneTimeSetUp() in /vsts/agent/_work/1/s/MyTests/TestsSetup.cs:line 66
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUpOrTearDownMethod(TestExecutionContext context, IMethodInfo method)
   at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUp(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.OneTimeSetUpCommand.<>c__DisplayClass0_0.<.ctor>b__0(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeTestCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeTestCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformOneTimeSetUp()
```

**Comment by mxschmitt** [comment]
Probably it depends on the website where you take a screenshots on, is it reproducible for you?
