### ISSUE TITLE
[BUG] NullReferenceException in IBrowser.NewContextAsync

### ISSUE THREAD

**Issue by Joe118** [microsoft/playwright-dotnet#2175]
**Context:**
- Playwright Version: 1.22.0
- Operating System: Windows 10
- .NET version: [e.g. .NET 5]
- Browser: Experienced in Chromium, likely in all browsers
- Extra: 
     Using Visual Studio Community Edition 2022
     Installed Microsoft.Playwright 1.22.0 via Package Manager via:
     > Install-Package Microsoft.Playwright -Version 1.22.0
     Did not remove existing package Microsoft.Playwright 1.15.3 (?)

Below is a small sample to demonstrate the problem. The NRE happens on the line with the comment /* NRE */

using System.Threading.Tasks;
using Microsoft.Playwright;

public static async Task<bool> GetAContext {IBrowser browser,
                                                                         BrowserNewContextOptions options)
{
...
            IBrowserContext ctx;
            try
            {
                ctx = await browser.NewContextAsync(options); /* NRE */
            }
            catch (Exception ex)
            {
                ReportExceptionAndNestedExceptions(ex);
                return false;
            }
            ...
            return true;
}

The version of Microsoft.Playwright is 1.22.0. Previous version is 1.15.3 (?)
This is similar to issue 2071

**Comment by mxschmitt** [comment]
What are your context options?

Could you try setting the `DEBUG=pw:browser` env var?

**Comment by Joe118** [comment]
Thanks @mxschmitt 

>> What are your context options?

The 'options' ref I pass to IBrowser.NewContextAsync() is null. I am relying on Playwright to initialize everything.

>> Could you try setting the DEBUG=pw:browser env var? This produces depending on the issue more verbose output.

I set DEBUG=pw:browser as you suggest and opened a new command.com to launch my program from. Are you sure it is DEBUG and not PWDEBUG? I saw PWDEBUG mentioned in docs but in the context of logging in the node.js side. After adding the  env var I don't see any more logging than before. I still get only this output:

06/12/2022 16:38:51:665: WARN: T6: DBD: BrowserNewContext failed: One or more errors occurred.
06/12/2022 16:38:51:666: INFO   : T6: DBD:	   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)

06/12/2022 16:38:51:666: INFO   : T6: DBD:	   at DojoPlatform.DojoBrowserDriver.BrowserNewContext(Interpreter interp, String varname, IBrowser browser, BrowserNewContextOptions options) in D:\dojodev\Dojo\DojoBrowserDriver\DojoBrowserObject.cs:line 207
06/12/2022 16:38:51:666: WARN: T6: DBD: Because Object reference not set to an instance of an object.
06/12/2022 16:38:51:666: INFO   : T6: DBD:	   at Microsoft.Playwright.Core.Browser.<NewContextAsync>d__33.MoveNext()

Are there log files from Playwright on disk somewhere? Could someone please help me find them? Many thanks!

I don't have logging set up in my C# program that hosts the Microsoft.Playwright.dll. I have been searching for examples of setting up Playwright logging in C# on the client side. Have not found anything relevant in docs.

The exception happens consistently for every call to IBrowser.NewContextAsync(). I'm stumped.

**Comment by mxschmitt** [comment]
> Are you sure it is DEBUG and not PWDEBUG?

Yes, its `DEBUG`, `PWDEBUG` is different and for opening the Playwright Inspector.

Could you maybe try running a very basic snippet? Aka something like this?

```csharp
using Microsoft.Playwright;

using var playwright = await Playwright.CreateAsync();
await using var browser = await playwright.Chromium.LaunchAsync();
var context = await browser.NewContextAsync();
var page = await context.NewPageAsync();
await page.GotoAsync("https://playwright.dev/dotnet");
await page.ScreenshotAsync(new PageScreenshotOptions { Path = "screenshot.png" });
```

> Are there log files from Playwright on disk somewhere? Could someone please help me find them? Many thanks!

There are not.

**Comment by Joe118** [comment]
@mxschmitt I am using visual studio 2022 community edition which does not have C# 6 apparently so had to modify the example slightly. Also, my main program is synchronous, so I am invoking the test from a synchronous method and using '.Result' to have the same circumstances as those that produce the error.

    using Microsoft.Playwright;
    using System.Threading.Tasks;

    public partial class DojoBrowserDriver
    {
        public static async Task<bool> TestSimple()
        {
            var playwright = await Playwright.CreateAsync();
            var browser = await playwright.Chromium.LaunchAsync();
            var context = await browser.NewContextAsync();
            var page = await context.NewPageAsync();
            await page.GotoAsync("https://playwright.dev/dotnet");
            await page.ScreenshotAsync(new PageScreenshotOptions { Path = "screenshot.png" });

            return true;
        }

        public static void TestWrapper()
        {
            bool res = TestSimple().Result;
        }
    }

The result is an exception as follows:

System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Playwright.Core.Browser.<NewContextAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DojoPlatform.DojoBrowserDriver.<TestSimple>d__0.MoveNext() in D:\dojodev\Dojo\DojoBrowserDriver\DojoBrowserTest.cs:line 25
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eagle._Commands.Object.Execute(Interpreter interpreter, IClientData clientData, ArgumentList arguments, Result& result) in D:\eagle.sources\Eagle\Library\Commands\Object.cs:line 2534

**Comment by Joe118** [comment]
I made some small changes to the test with the result being the same exception:

   public partial class DojoBrowserDriver
    {
        public static async Task TestSimple()
        {
            var playwright = await Playwright.CreateAsync();
            var browser = await playwright.Chromium.LaunchAsync();
            var context = await browser.NewContextAsync();
            var page = await context.NewPageAsync();
            await page.GotoAsync("https://playwright.dev/dotnet");
            await page.ScreenshotAsync(new PageScreenshotOptions { Path = "screenshot.png" });

            /* return true; */
        }

        public static void TestWrapper()
        {
            /* bool res = */ TestSimple().Wait();
        }
    }

And the stack trace:

 System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Playwright.Core.Browser.<NewContextAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DojoPlatform.DojoBrowserDriver.<TestSimple>d__0.MoveNext() in D:\dojodev\Dojo\DojoBrowserDriver\DojoBrowserTest.cs:line 25
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at DojoPlatform.DojoBrowserDriver.TestWrapper() in D:\dojodev\Dojo\DojoBrowserDriver\DojoBrowserTest.cs:line 36
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eagle._Commands.Object.Execute(Interpreter interpreter, IClientData clientData, ArgumentList arguments, Result& result) in D:\eagle.sources\Eagle\Library\Commands\Object.cs:line 2534
   
   Finally, I checked that env variable DEBUG was set to pw:browser inside my program and it is.

**Comment by Joe118** [comment]
Can someone please tell me what is the newest package release that was released before issue #2071  was submitted? Thanks

**Comment by campersau** [comment]
> Did not remove existing package Microsoft.Playwright 1.15.3 (?)

It should but you can just check the csproj to make sure that there is only one `PackageReference` to `Microsoft.Playwright`.

You can also try to remove the `bin`/`obj` folders and rebuild the project.

It shouldn't be the problem but maybe run [`pwsh bin\Debug\netX\playwright.ps1 install`](https://playwright.dev/dotnet/docs/intro) again.

> Can someone please tell me what is the newest package release that was released before issue https://github.com/microsoft/playwright-dotnet/issues/2071 was submitted?

I think that's version [`1.18.1`](https://github.com/microsoft/playwright-dotnet/releases/tag/v1.18.1)

**Comment by Joe118** [comment]
> It should but you can just check the csproj to make sure that there is only one PackageReference to Microsoft.Playwright.

Confirmed -- only one

**Comment by Joe118** [comment]
Thanks @slang25 I tried your suggestion. No change in result.

**Comment by Joe118** [comment]
Finally was able to retrieve the output from stdout, @mxschmitt -- here is EVERYTHING that it printed:

2022-06-15T05:11:57.687Z pw:browser <launching> C:\Users\jyl\AppData\Local\ms-playwright\chromium-920619\chrome-win\chrome.exe --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --user-data-dir=C:\Users\jyl\AppData\Local\Temp\playwright_chromiumdev_profile-WJq5wm --remote-debugging-pipe --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --no-startup-window
2022-06-15T05:11:57.695Z pw:browser <launched> pid=12272

**Comment by mxschmitt** [comment]
This unfortunate does not help much. Let's go back to the snippet which I sent you, please only execute this file: https://github.com/microsoft/playwright-dotnet/issues/2175#issuecomment-1153617150

I also saw that you are using `.Result` which might end up in such errors.

**Comment by Joe118** [comment]
@mxschmitt 

I'm using VS2022 Community Edition. I have DEBUG=pw:browser set.

I created a new project, selected Console Application, and Net 5.0 as target framework. Copied the minimal test you provided into Program.cs and built. Everything built cleanly, and when I ran the executable the output below was produced and the program exited with status code 0.

All the details:

**The program**:
using Microsoft.Playwright;

using var playwright = await Playwright.CreateAsync();
await using var browser = await playwright.Chromium.LaunchAsync();
var context = await browser.NewContextAsync();
var page = await context.NewPageAsync();
await page.GotoAsync("https://playwright.dev/dotnet");
await page.ScreenshotAsync(new PageScreenshotOptions { Path = "screenshot.png" });

**Building**:
Here is the PlaywrightTest.csproj:

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Playwright" Version="1.22.0" />
  </ItemGroup>

</Project>

Everything built cleanly

**The output**:

2022-06-19T18:27:51.338Z pw:browser <launching> C:\Users\jyl\AppData\Local\ms-playwright\chromium-1005\chrome-win\chrome.exe --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=C:\Users\jyl\AppData\Local\Temp\playwright_chromiumdev_profile-5oWqvo --remote-debugging-pipe --no-startup-window
2022-06-19T18:27:51.349Z pw:browser <launched> pid=9828
2022-06-19T18:27:55.303Z pw:browser [pid=9828] <gracefully close start>
2022-06-19T18:27:55.331Z pw:browser [pid=9828] <process did exit: exitCode=0, signal=null>
2022-06-19T18:27:55.331Z pw:browser [pid=9828] starting temporary directories cleanup
2022-06-19T18:27:55.340Z pw:browser [pid=9828] finished temporary directories cleanup
2022-06-19T18:27:55.340Z pw:browser [pid=9828] <gracefully close end>

D:\playwrightdemo\bin\Debug\net6.0\playwrightdemo.exe (process 11032) exited with code 0.

**Comment by Joe118** [comment]
I noted that the console application created around the test program is targeting Net 5.0, while the environment where I am observing the NRE, the build is targeting Net Framework 4.8 and the code interfacing with Microsoft.Playwright is being built as a class library. The main program is a Windows Application.

Is this configuration supported by Microsoft.Playwright?

Thanks for all your help!

**Comment by campersau** [comment]
Do you also have a nuget reference to `Microsoft.Playwright` in the Windows Application (what kind of Windows Application is it?)?
If yes, can you please check if that is also referencing the new version? If not can you add the same nuget reference and run it again?
