### ISSUE TITLE
[Question]: Microsoft.Playwright.PlaywrightException: Process exited

### ISSUE THREAD

**Issue by cigjonser** [microsoft/playwright-dotnet#2225]
Hi,

I'm having a problem getting Playwright to work on my deployment machine. Works great on the local machine.

Playwright version: 1.24.0
Windows: Running on VirtualBox: 32 bit, Windows 10 Pro, Version 21H1, OS build 19043.1826
Deployed by publishing to folder and copying the files. (Config: Release, Any CPU, Framework: net6.0-windows, Mode: Framework-dependent, Runtime: Portable)

called via:
                playwright = await Playwright.CreateAsync();

Getting this exception:

Microsoft.Playwright.PlaywrightException: Process exited
   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](String guid, String method, Object args) in /_/src/Playwright/Transport/Connection.cs:line 167
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 477
   at Microsoft.Playwright.Transport.Channels.Root.InitializeAsync() in /_/src/Playwright/Transport/Channels/Root.cs:line 47
   at Microsoft.Playwright.Playwright.CreateAsync() in /_/src/Playwright/Playwright.cs:line 57
   at DataTransfer.Form1.Collect() in C:\Users\Owner\source\repos\DataTransfer\DataTransfer\Form1.cs:line 148
   at DataTransfer.Form1.startButton_Click(Object sender, EventArgs e) in C:\Users\Owner\source\repos\DataTransfer\DataTransfer\Form1.cs:line 1180
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)

**Comment by mxschmitt** [comment]
Windows 10 32 is not supported, thats most likely the issue. Playwright only supports 64 bit.

**Comment by cigjonser** [comment]
I was afraid of that. Thanks.
