### ISSUE TITLE
[Feature] Allow to specify custom drivers path (for security reasons)

### ISSUE THREAD

**Issue by BeniFreitag** [microsoft/playwright-dotnet#2317]
We use playwright to serve PDF files in an ASP.NET Web Application (currently .NET 4.8 with IIS but soon .NET core with IIS).

For security reasons all files of the Web Application are on a separate drive at `P:\Projects\ProjectName\Website`. On that drive `Users` have no access, just the App-Pool user can access files of the appropriate Project itself. This way all applications are isolated from each other. There were security bulletins in the last years highly recommending that approach.

In that setup Playwright fails, because node can't open files in `P:\Projects\ProjectName\.playwright\`, unless the App-Pool user has _Read_-Permission on both `P:\` and `P:\Projects`. Otherwise it throws `PlaywrightException: Process exited` (details below). But this breaks the security aspects of isolating each application completely.

It's probably an issue of node which can't handle permissions just granted on a deeper level than on the root of a drive. Probably it's not on the top priorities of node to ever fix that.

**Suggestion:**
It would be valuable if the location of the `.playwright` directory could be specified in this case. Currently the `.playwright` directory must always be in the Application's directory. If it could be at a custom location, security can be configured as needed for node.

This is related to #2241 but affects both .NET 4.8 **and** ASP.NET Core. I could imagine that other projects will also benefit, if that `.playwright` directory could be in a custom path, for various reasons. #2241 would already solve that need.

Exception details (captured in `transport.LogReceived`):
```
node:internal/fs/utils:345 
    throw err; 
    ^ 
 
Error: EPERM: operation not permitted, lstat 'P:\' 
    at Object.realpathSync (node:fs:2461:5) 
    at toRealPath (node:internal/modules/cjs/loader:394:13) 
    at Function.Module._findPath (node:internal/modules/cjs/loader:550:22) 
    at resolveMainPath (node:internal/modules/run_main:19:25) 
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:71:24) 
    at node:internal/main/run_main_module:17:47 { 
  errno: -4048, 
  syscall: 'lstat', 
  code: 'EPERM', 
  path: 'P:\\' 
}
```

**Comment by pnocera** [comment]
I'm hitting the same issue here. Do you guys have some hints on how to overcome this ?
I'd like to still benefit from the lib updates.

**Comment by bkbartonDesign** [comment]
I'm looking for solutions to the same thing. +1

**Comment by zubairkhakwani** [comment]
Does anyone know any workaround?

**Comment by Cereal-Killa** [comment]
Any tips to get it working on .NET 4.8?
I'm on a similar situation however the exception stack trace does not say it's a driver issue, there is no relevant information:

```
Process exited
Stack trace: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Playwright.Transport.Connection.d__40`1.MoveNext() in /_/src/Playwright/Transport/Connection.cs:line 206
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Playwright.Transport.Connection.d__52`1.MoveNext() in /_/src/Playwright/Transport/Connection.cs:line 535
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Playwright.Transport.Connection.d__43.MoveNext() in /_/src/Playwright/Transport/Connection.cs:line 245
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Playwright.Playwright.d__0.MoveNext() in /_/src/Playwright/Playwright.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

**Comment by filzrev** [comment]
Playwright `1.41` or later support custom driver path by `PLAYWRIGHT_DRIVER_SEARCH_PATH` environment variable.
Could this feature solve reported issue?

**Comment by Cereal-Killa** [comment]
> Playwright `1.41` or later support custom driver path by `PLAYWRIGHT_DRIVER_SEARCH_PATH` environment variable. Could this feature solve reported issue?

Thank you, I did try that without any luck, the exception per se does not mention a driver location issue, and I placed a copy of that .playwright folder just about everywhere, could be just about anything...
