### ISSUE TITLE
[Bug] Playwright Crashing When doing _page.TextContent(selector);

### ISSUE THREAD

**Issue by infinitejest69** [microsoft/playwright-dotnet#2368]
Tech Stack
Playwright 1.27.2
Nunit 4.2.1
Specflow 3.9.74
browser = Chrome

Description:
This intermittently happens but when doing a get using a selector playwright in chrome will crash, i understand locators are the preferred approach i have not had time to refactor my test suite to use locators over Element handles. if i debug the test in VS i see it pass and the value be returned. is there an easy way to remove playwright and reinstall to see if something environmental got corrupted 

I am getting text from a simple element and playwright will crash the log does not tell me much

Method used
```C#
      public async Task<string> BaseGetTextContent(string selector)
        {
            try
            {
                var result = await _page.TextContentAsync(selector);
                return result.Trim();
            }
            catch (TimeoutException e)
            {
                LogTimeout(e);
                return null;
            }
        }
```

![image](https://user-images.githubusercontent.com/9976197/199979575-cd59e6ac-fee1-4660-a1d9-309a2ec93c27.png)

```
Building Test Projects
Starting test discovery for requested test run
========== Starting test discovery ==========
NUnit Adapter 4.2.0.0: Test discovery starting
NUnit Adapter 4.2.0.0: Test discovery complete
========== Test discovery finished: 854 Tests found in 2.5 sec ==========
========== Starting test run ==========
NUnit Adapter 4.2.0.0: Test execution started
Running selected tests in C:\Users\<Name>\source\repos\Test_UI\TestUI\bin\Debug\net6.0\TestUI.dll
   NUnit3TestExecutor discovered 1 of 1 NUnit test cases using Current Discovery mode, Non-Explicit run
2022-11-04T12:50:20.034Z pw:browser <launching> C:\Program Files\Google\Chrome\Application\chrome.exe --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox --user-data-dir=C:\Users\ANDREW~1\AppData\Local\Temp\playwright_chromiumdev_profile-4dCj1B --remote-debugging-pipe --no-startup-window
2022-11-04T12:50:20.049Z pw:browser <launched> pid=17344
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. Microsoft.Playwright.PlaywrightException: Target closed
=========================== logs ===========================
waiting for selector "ctx-overlay >> mat-panel-title"
============================================================
   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](String guid, String method, Object args) in /_/src/Playwright/Transport/Connection.cs:line 163
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 482
   at Microsoft.Playwright.Transport.Channels.FrameChannel.TextContentAsync(String selector, Nullable`1 timeout, Nullable`1 strict) in /_/src/Playwright/Transport/Channels/FrameChannel.cs:line 587
   at TestUI.PageObjects.BasePage.BaseGetTextContent(String selector) in C:\Users\<Test>\source\repos\Test_UI\TestUI\PageObjects\BasePage.cs:line 377
   at TestUI.ComponentsModel.Overlay.GetMatPanelTitle() in C:\Users\<Test>\source\repos\Test_UI\TestUI\ComponentsModel\Common\Overlay.cs:line 260
   at TestUI.Steps.LocaleSteps.ThenISeeLocalesSelectedSummaryShows(String summaryMessage) in C:\Users\<Test>\source\repos\Test_UI\TestUI\Steps\LocaleManager\LocaleSteps.cs:line 85
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

========== Test run aborted: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in < 1 ms ==========
```

**Comment by mxschmitt** [comment]
Can you share a repro for this? This would be helpful to debug this further.

Alternatively you can try setting the `DEBUG=pw:browser` environment variable, which will print the browser stdout/stderr.

If this does not show anything meaningful, setting the `DEBUG=pw:protocol` env var might help as well.

Happy to take a look at the output once provided thanks!

**Comment by infinitejest69** [comment]
@mxschmitt 
Hi i sorry i have been off work for a while so forget to update this.
I cant share a repo and have ran this test with a debug set to protocol but the log attached

[log fail.txt](https://github.com/microsoft/playwright-dotnet/files/10031080/log.fail.txt)

**Comment by infinitejest69** [comment]
If anyone comes across this i solved the issue and it was entirely my own fail.
one of the methods in the call stack was  returning "asnyc void" not "async Task", changed and no longer having playwright crash and close
