### ISSUE TITLE
How should the runtime environment be used?

### ISSUE THREAD

**Issue by bbhxwl** [microsoft/playwright-dotnet#2418]
···
FROM mcr.microsoft.com/dotnet/runtime:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/playwright:v1.28.0-focal AS playwright
RUN npx playwright install

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["AutoLoginMTeam/AutoLoginMTeam.csproj", "AutoLoginMTeam/"]
RUN dotnet restore "AutoLoginMTeam/AutoLoginMTeam.csproj"
COPY . .
WORKDIR "/src/AutoLoginMTeam"
RUN dotnet build "AutoLoginMTeam.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "AutoLoginMTeam.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "AutoLoginMTeam.dll"]

···

···
2022-12-04T16:37:41.330052958Z Unhandled exception. Microsoft.Playwright.PlaywrightException: Executable doesn't exist at /root/.cache/ms-playwright/webkit-1735/pw_run.sh
2022-12-04T16:37:41.330080125Z ╔════════════════════════════════════════════════════════════╗
2022-12-04T16:37:41.330083583Z ║ Looks like Playwright was just installed or updated.       ║
2022-12-04T16:37:41.330085458Z ║ Please run the following command to download new browsers: ║
2022-12-04T16:37:41.330087167Z ║                                                            ║
2022-12-04T16:37:41.330088958Z ║     pwsh bin/Debug/netX/playwright.ps1 install             ║
2022-12-04T16:37:41.330090542Z ║                                                            ║
2022-12-04T16:37:41.330092333Z ║ <3 Playwright Team                                         ║
2022-12-04T16:37:41.330094417Z ╚════════════════════════════════════════════════════════════╝
2022-12-04T16:37:41.330096542Z    at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](String guid, String method, Object args) in /_/src/Playwright/Transport/Connection.cs:line 163
2022-12-04T16:37:41.330098500Z    at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal)
2022-12-04T16:37:41.330100375Z    at Microsoft.Playwright.Core.BrowserType.LaunchAsync(BrowserTypeLaunchOptions options) in /_/src/Playwright/Core/BrowserType.cs:line 61
2022-12-04T16:37:41.330102167Z    at Program.<Main>$(String[] args) in /src/AutoLoginMTeam/Program.cs:line 19
2022-12-04T16:37:41.330104125Z    at Program.<Main>(String[] args)

···

**Comment by mxschmitt** [comment]
what is the question? You need to install browsers via `pwsh bin/Debug/netX/playwright.ps1 install`
