### ISSUE TITLE
xUnit test run crashes in docker container with playwright base image.

### ISSUE THREAD

**Issue by quldude** [microsoft/playwright-dotnet#2424]
### Your question

I have the following code to launch chromium with playwright ver 1.28 and xunit:
```
public sealed class SuiteFixture : IAsyncLifetime, IDisposable
{
     .......
public async Task InitializeAsync()
    {
        _playwrightInstance = await Playwright.CreateAsync();

        _browser = await _playwrightInstance.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
        {
            Headless = true,
            Args = new List<string> { "--start-maximized " }
        });

        Context = await _browser.NewContextAsync(
           new BrowserNewContextOptions()
           {
               UserAgent = "XYZ"
           });
    }
.....
```

But when this runs in a docker container with playwright/dotnet:v1.28.0-focal as base image, I get the following error for command `dotnet test Sample.E2E.Tests.dll --logger "console;verbosity=detailed"`:
```
[xUnit.net 00:00:01.69]   Discovered:  Sample.E2E.Tests (found 2 test cases)
[xUnit.net 00:00:01.69]   Starting:    Sample.E2E.Tests (parallel test collections = on, max threads = unlimited)
The active test run was aborted. Reason: Test host process crashed

Test Run Aborted with error System.Exception: One or more errors occurred.
---> System.Exception: Unable to read beyond the end of the stream.
at System.IO.BinaryReader.Read7BitEncodedInt()
at System.IO.BinaryReader.ReadString()
at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable()
at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action`1 errorHandler, CancellationToken cancellationToken)
--- End of inner exception stack trace ---.
```

Not sure what is causing the crash. When I run locally on a windows machine, it works fine. I have 2 test collections that use the same fixture and the collections run in parallel. Does `await Playwright.CreateAsync()` need to be called only once and not by every test class?

**Comment by mxschmitt** [comment]
This exception does not look like its coming from Playwright. Maybe try to create a minimal repro to narrow it down further?

**Comment by quldude** [comment]
this was due to container resource limitation. once cpu and memory were increased, then tests ran in parallel.
