### ISSUE TITLE
System.MissingMethodException : Method not found: Microsoft.Playwright.BrowserTypeLaunchOptions[BUG]

### ISSUE THREAD

**Issue by bubbanoosh** [microsoft/playwright-dotnet#2505]
**Context:**
- Playwright Version: 1.31.1
- Operating System: Windows 10
- .NET version: .net7.0
- Browser: All

New to PW, and I have set up a dotnet nunit project running in VS2022.
- I've added the dependencies Microsoft.Playwright.NUnit v1.31.1
- I've installed the browsers 'pwsh bin/Debug/net7.0/playwright.ps1 install'
- I've verified the browsers are there 'C:\Users\xxx\AppData\Local\ms-playwright'

I've built, clean, rebuilt, etc but when I run tests I get:

`System.MissingMethodException : Method not found: 'Microsoft.Playwright.BrowserTypeLaunchOptions Microsoft.Playwright.TestAdapter.PlaywrightSettingsProvider.get_LaunchOptions()'.`

This happens also with SAMPLE TEST taken from playwright.dev

```cs
[Parallelizable(ParallelScope.Self)]
[TestFixture]
public class Tests : PageTest
{
    [Test]
    public async Task ShouldHaveTheCorrectSlogan()
    {
        await Page.GotoAsync("https://playwright.dev");
        await Expect(Page.Locator("text=enables reliable end-to-end testing for modern web apps")).ToBeVisibleAsync();
    }
}
```

Stacktrace
```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed ShouldHaveTheCorrectSlogan [492 ms]
  Error Message:
   System.MissingMethodException : Method not found: 'Microsoft.Playwright.BrowserTypeLaunchOptions Microsoft.Playwright.TestAdapter.PlaywrightSettingsProvider.get_LaunchOptions()'.
  Stack Trace:
     at Microsoft.Playwright.NUnit.BrowserService.<>c__DisplayClass4_0.<<Register>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Playwright.NUnit.BrowserService.<>c__DisplayClass4_0.<Register>b__0()
   at Microsoft.Playwright.NUnit.WorkerAwareTest.RegisterService[T](String name, Func`1 factory) in /_/src/Playwright.NUnit/WorkerAwareTest.cs:line 55
   at Microsoft.Playwright.NUnit.BrowserTest.BrowserSetup() in /_/src/Playwright.NUnit/BrowserTest.cs:line 46
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUpOrTearDownMethod(TestExecutionContext context, IMethodInfo method)
   at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUp(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.SetUpTearDownCommand.<>c__DisplayClass0_0.<.ctor>b__0(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.DelegatingTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
```
Please help :(

**Comment by mxschmitt** [comment]
Can you try installing `Microsoft.Playwright` dependency manually? `Microsoft.Playwright` is a dependency of `Microsoft.Playwright.NUnit` so it should be installed automatically, but isn't it seems like in your case.

**Comment by bubbanoosh** [comment]
So I added `Microsoft.Playwright` manually but not change...
Still the same exception :/
Here's my csproj

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <Platforms>x64</Platforms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.5.0" />
    <PackageReference Include="Microsoft.Playwright" Version="1.31.1" />
    <PackageReference Include="Microsoft.Playwright.NUnit" Version="1.31.1" />
    <PackageReference Include="Microsoft.Playwright.TestAdapter" Version="1.31.1" />
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.4.0" />
    <PackageReference Include="NUnit.Analyzers" Version="3.6.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="3.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```

**Comment by mxschmitt** [comment]
I tried on .NET 7 and was not able to repro. You create always a new project for it? Could you try doing it without VS2022? So just follow these steps: https://playwright.dev/dotnet/docs/intro to run a first test.

**Comment by bubbanoosh** [comment]
Sorry I got sidetracked with other work.
I did create a new project in VS2022 as described however it failed as mentioned.

HOWEVER, upon starting from scratch again it finally worked :)

Thanks for your time!

(^_^)
