### ISSUE TITLE
[BUG] Microsoft.Playwright.PlaywrightException: net::ERR_ABORTED; maybe frame was detached? after page reload

### ISSUE THREAD

**Issue by DaveSenn** [microsoft/playwright-dotnet#2514]
**Context:**
- Microsoft.Playwright 1.31.1
- Operating System: Windows 10 21H2
- .NET version: .NET 7
- Browser: Chrome

**Code Snippet**

```cs
using System.Threading.Tasks;
using Microsoft.Playwright;

class Program
{
    public static async Task Main()
    {
            var playwright  = await Playwright.CreateAsync();
            var browser = await playwright.Chromium.LaunchAsync( new()
            {
                Headless = false
            } );
            var page = await browser.NewPageAsync( new()
            {
                ScreenSize = new()
                {
                    Height = 1200, Width = 2000
                },
                BaseURL ="http://localhost:48200" ,
                ExtraHTTPHeaders = new Dictionary<String, String>
                {
                    { "Tenant", "Logisoft" },
                    { "User", "ArgosEEUser" },
                    { "FunctionGroup", "Zeus" }
                }
            } );
            await page.GotoAsync( "http://localhost:48200" );
            await page.GetByRole( AriaRole.Link, new() { Name = "Benutzerprofil" } ).ClickAsync();

            for ( var i = 0; i < 100; i++ )
            {
                await page.Locator( "#safe-user-profile" ).ClickAsync(); // button click triggers a ajax request followed by a page reload
                await Task.Delay( 10 );
                await page.WaitForLoadStateAsync( LoadState.NetworkIdle );
                await page.ReloadAsync( new()
                {
                    WaitUntil = WaitUntilState.NetworkIdle
                } );
            }
    }
}
```

**Describe the bug**

The above code results in thsi exception:

````
Microsoft.Playwright.PlaywrightException: net::ERR_ABORTED; maybe frame was detached?
=========================== logs ===========================
waiting for navigation until "networkidle"
============================================================
   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](String guid, String method, Dictionary`2 dictionary) in /_/src/Playwright/Transport/Connection.cs:line 143
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 465
   at Microsoft.Playwright.Core.Page.ReloadAsync(PageReloadOptions options) in /_/src/Playwright/Core/Page.cs:line 684
   at Project.Tests.UIOnly.UserProfileTest.ChangeUserProfileOptions() in \Tests\UIOnly\UserProfileTest.cs:line 74
```


The exception is caused by `ReloadAsync`.
Maybe the problem has something todo with the actions performed by the tested web application.
After clicking the button (safe-user-profile) the web application sends a POST request to a backend API. When the request returns a success code (is the case here) the UI triggers a reload of the current page with `location.reload()` (JS).
The exception does not occur each time but quite often.

**Comment by mxschmitt** [comment]
Can you provide us a self contained reproducible which we can run locally?

**Comment by DaveSenn** [comment]
[Repro.zip](https://github.com/microsoft/playwright-dotnet/files/10995587/Repro.zip)
@mxschmitt kleine mvc app. profil um alles zu starten: Repro.sln.startup.json

**Comment by mxschmitt** [comment]
Sorry for the slow response. I was running it locally but it was passing for me all the time. Even increased the loop to 1000. How often can you reproduce it on your system? Is this like something 1/100 or all the time?

**Comment by phatle1** [comment]
I'm facing this issue when run on parallel, work fine without parallel, please help.
