### ISSUE TITLE
[BUG] Regex flags (RegexOptions) ignored when passed to ILocatorAssertions.ToHaveAttributeAsync()

### ISSUE THREAD

**Issue by cjohnson** [microsoft/playwright-dotnet#2581]
**Context:**
- Playwright Version: 1.33.0
- Operating System: Windows
- .NET version: .NET 6
- Browser: All

**Code Snippet**
```cs
public async Task ShouldSupportToHaveAttributeByRegexAsync()
{
    await Page.SetContentAsync("<img src=\"https://PLAYWRIGHT.dEV/mEDIa/photo.JPG?queryString=true\"/>");
    await Expect(Page.Locator("img")).ToHaveAttributeAsync("src", new Regex("https://playwright.dev/media/photo", RegexOptions.IgnoreCase));
}
```

**Stack Trace**
```
Failed ShouldSupportToHaveAttributeByRegexAsync [7 s]
  Error Message:
   Microsoft.Playwright.PlaywrightException : Locator expected to have attribute 'src' matching regex 'https://playwright.dev/media/photo'
But was: 'https://PLAYWRIGHT.dEV/mEDIa/photo.JPG?queryString=true'
Call log:
LocatorAssertions.ToHaveAttributeAsync with timeout 5000ms
waiting for Locator("img")
  locator resolved to <img src="https://PLAYWRIGHT.dEV/mEDIa/photo.JPG?quer./>
  unexpected value "https://PLAYWRIGHT.dEV/mEDIa/photo.JPG?queryString=true"
  locator resolved to <img src="https://PLAYWRIGHT.dEV/mEDIa/photo.JPG?quer./>
  unexpected value "https://PLAYWRIGHT.dEV/mEDIa/photo.JPG?queryString=true"
  locator resolved to <img src="https://PLAYWRIGHT.dEV/mEDIa/photo.JPG?quer./>
  unexpected value "https://PLAYWRIGHT.dEV/mEDIa/photo.JPG?queryString=true"
  locator resolved to <img src="https://PLAYWRIGHT.dEV/mEDIa/photo.JPG?quer./>
  unexpected value "https://PLAYWRIGHT.dEV/mEDIa/photo.JPG?queryString=true"
  locator resolved to <img src="https://PLAYWRIGHT.dEV/mEDIa/photo.JPG?quer./>
  unexpected value "https://PLAYWRIGHT.dEV/mEDIa/photo.JPG?queryString=true"
  locator resolved to <img src="https://PLAYWRIGHT.dEV/mEDIa/photo.JPG?quer./>
  unexpected value "https://PLAYWRIGHT.dEV/mEDIa/photo.JPG?queryString=true"
  locator resolved to <img src="https://PLAYWRIGHT.dEV/mEDIa/photo.JPG?quer./>
  unexpected value "https://PLAYWRIGHT.dEV/mEDIa/photo.JPG?queryString=true"
  locator resolved to <img src="https://PLAYWRIGHT.dEV/mEDIa/photo.JPG?quer./>
  unexpected value "https://PLAYWRIGHT.dEV/mEDIa/photo.JPG?queryString=true"
  locator resolved to <img src="https://PLAYWRIGHT.dEV/mEDIa/photo.JPG?quer./>
  unexpected value "https://PLAYWRIGHT.dEV/mEDIa/photo.JPG?queryString=true"
  Stack Trace:
     at Microsoft.Playwright.Core.AssertionsBase.ExpectImplAsync(String expression, FrameExpectOptions expectOptions, Object expected, String message) in C:\Users\collin.johnson\source\repos\playwright-dotnet\src\Playwright\Core\AssertionsBase.cs:line 89
   at Microsoft.Playwright.Core.AssertionsBase.ExpectImplAsync(String expression, ExpectedTextValue[] expectedText, Object expected, String message, FrameExpectOptions options) in C:\Users\collin.johnson\source\repos\playwright-dotnet\src\Playwright\Core\AssertionsBase.cs:line 63
   at Microsoft.Playwright.Core.AssertionsBase.ExpectImplAsync(String expression, ExpectedTextValue textValue, Object expected, String message, FrameExpectOptions options) in C:\Users\collin.johnson\source\repos\playwright-dotnet\src\Playwright\Core\AssertionsBase.cs:line 55
   at Microsoft.Playwright.Tests.Assertions.LocatorAssertionsTests.ShouldSupportToHaveAttributeByRegexAsync() in C:\Users\collin.johnson\source\repos\playwright-dotnet\src\Playwright.Tests\Assertions\LocatorAssertionsTests.cs:line 466
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.DelegatingTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
```

**Describe the bug**

While playwright seems to process Regex objects without flags fine, when a flag is passed in, such as IgnoreCase, it seems that the matching operation is still using a case-sensitive setting.

**Comment by mxschmitt** [comment]
Thanks for reporting, I was able to reproduce.
