### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by thisisnewbi** [microsoft/playwright-dotnet#2614]
playwright nunit version 1.33.0
windows version 10
browser chrome latest version

when i m executing the dotnet test command for my test with specflow i m getting below error 
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. Microsoft.Playwright.PlaywrightException: Browser has been closed
   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](String guid, String method, Dictionary`2 dictionary, Boolean keepNulls) in /_/src/Playwright/Transport/Connection.cs:line 213
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal)
   at Microsoft.Playwright.Core.Frame.QuerySelectorAllAsync(String selector) in /_/src/Playwright/Core/Frame.cs:line 481

**Comment by yury-s** [comment]
Please follow the bug template and provide a self-contained reproducible example which we could run locally. Otherwise we have no clue what your test does and why it's crashing.

**Comment by AndyAyersMS** [comment]
If this problem was seen with .NET 8 Preview 5 it may be the same as in https://github.com/dotnet/runtime/issues/87628

I suspect (but haven't yet proved) that the stack inspection that playwright is doing is fragile and gets broken when running with the new Dynamic PGO capabilities in .NET 8.
