### ISSUE TITLE
[Question]: Browser Error in Github Codespace

### ISSUE THREAD

**Issue by angelo-loria** [microsoft/playwright-dotnet#2630]
### Your question

Hi,
I've setup a project for API testing. My code is exactly what is laid out in the [API testing docs page](https://playwright.dev/dotnet/docs/api-testing). I followed the [installation instructions here.](https://playwright.dev/dotnet/docs/intro) This works great on my local machine but I'm having trouble getting the tests to execute in a Github Codepsace.

When I run `dotnet test` from the terminal in my Codespace, I get this error-
```
  Failed ShouldCreateBugReport [< 1 ms]
  Error Message:
   System.ArgumentException : Invalid browser name: /vscode/bin/linux-x64/695af097c7bd098fbf017ce3ac85e09bbc5dda06/bin/helpers/browser.sh
  Stack Trace:
     at Microsoft.Playwright.TestAdapter.PlaywrightSettingsProvider.ValidateBrowserName(String browserName) in /_/src/Playwright.TestAdapter/PlaywrightSettingsProvider.cs:line 102
   at Microsoft.Playwright.TestAdapter.PlaywrightSettingsProvider.get_BrowserName() in /_/src/Playwright.TestAdapter/PlaywrightSettingsProvider.cs:line 45
   at Microsoft.Playwright.NUnit.PlaywrightTest.PlaywrightSetup() in /_/src/Playwright.NUnit/PlaywrightTest.cs:line 44
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUpOrTearDownMethod(TestExecutionContext context, IMethodInfo method)
   at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUp(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.SetUpTearDownCommand.<>c__DisplayClass0_0.<.ctor>b__0(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.DelegatingTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
```

Any thoughts on this? My Codespace is a standard Github Codespace- 4 core, 8gb, 32gb storage.

**Comment by angelo-loria** [comment]
Running `sudo dotnet test` resolved this.
