### ISSUE TITLE
[BUG] ClickAsync() on popup window that closes itself causes exception

### ISSUE THREAD

**Issue by coderb** [microsoft/playwright-dotnet#2684]
### System info
- Playwright Version: v1.36
- Operating System: All
- Browser: All
- Other info:

A popup window that includes a button which closes the window sometimes causes an Exception in playwright.

It happens about half the time (probably a race condition that depends on how fast the browser window is closed).

### Source code

                var popup = await page.RunAndWaitForPopupAsync(async () => { 
                    await buttonThatOpensPopupWindow.ClickAsync();
                });
                await popup.WaitForLoadStateAsync();
                await popup.ClickAsync("#btnOk");

**Expected**

no exception

**Actual**
```
============================================================
Exception: PlaywrightException: Target closed
=========================== logs ===========================
waiting for Locator("#btnOk")
  locator resolved to <a class="button-primary" onclick="Foo…>…</a>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
============================================================
   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](String guid, String method, Dictionary`2 dictionary, Boolean keepNulls) in /_/src/Playwright/Transport/Connection.cs:line 192
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal)
   at Test.Do(IPage page) in c:\source\Test.cs:line 163
```

**Comment by mxschmitt** [comment]
Can you share a reproducible which demonstrates the issue?

**Comment by coderb** [comment]
unfortunately it's with a financial website that requires and account and login.

my code is very basic and the relevant part is above.  is there some other way to provide you with any additional info you need to address the issue?

btw- thanks for your hard work, the project is fantastic.

**Comment by coderb** [comment]
additional info:
also present in 1.37.1
seems to only happen w/firefox

**Comment by mxschmitt** [comment]
Thanks for filing! I can reproduce actually with this code which passes in CR and WK but fails in FF:

```csharp
using Microsoft.Playwright;

using var playwright = await Playwright.CreateAsync();
await using var browser = await playwright.Webkit.LaunchAsync(new BrowserTypeLaunchOptions() { Headless = false });
var context = await browser.NewContextAsync();
var page = await context.NewPageAsync();
await page.GotoAsync("https://example.com");

await context.RouteAsync("**/popup.html", async (route) =>
{
    await route.FulfillAsync(new()
    {
        Status = 200,
        ContentType = "text/html",
        Body = "<button id=btnOk onclick=\"window.close();\">Close Me</button>"
    });
});

await page.SetContentAsync(@"
    <button onclick=""window.open('https://example.com/popup.html')"" id=button>Button</button>
    <script>
        button.addEventListener('click', () => {
            const popup = window.open('https://example.com/popup.html');
            popup.onload = () => {
                popup.document.querySelector('button').click();
            };
        });
    </script>
");

var popup = await page.RunAndWaitForPopupAsync(async () => { 
    await page.GetByRole(AriaRole.Button, new() { Name = "Button" }).ClickAsync();
});
await popup.GetByRole(AriaRole.Button, new() { Name = "Close Me" }).ClickAsync();
```

No action needed from your side anymore.
