### ISSUE TITLE
[BUG] LocalUtils does not guard against null on LocalUtilsInitializer.DeviceDescriptors

### ISSUE THREAD

**Issue by martincostello** [microsoft/playwright-dotnet#2731]
### System info
- Playwright Version: [v1.39]
- Operating System: All
- Browser: All
- Other info: None

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/martincostello/dotnet-playwright-tests/commit/2a11d13021d9f83b3a408429e1d92af9558654a3

**Steps**

- Clone the repository above at the given commit
- Run `build.ps1`

The issue appears to be intermittent, so may take several times to repro. I'm also not sure _why_ the value is null - this exception could be the symptom of a different issue, rather than just the lack of a null guard.

**Expected**

No exception is thrown.

**Actual**

An exception is thrown from this code.

https://github.com/microsoft/playwright-dotnet/blob/eade3f5894752dc64cc1c242a37f03b39355c625/src/Playwright/Core/LocalUtils.cs#L41

```text
Microsoft.Playwright.PlaywrightException : System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Playwright.Core.LocalUtils..ctor(IChannelOwner parent, String guid, LocalUtilsInitializer initializer) in /_/src/Playwright/Core/LocalUtils.cs:line 41
   at Microsoft.Playwright.Transport.Connection.CreateRemoteObject(String parentGuid, ChannelOwnerType type, String guid, Nullable`1 initializer) in /_/src/Playwright/Transport/Connection.cs:line 355
   at Microsoft.Playwright.Transport.Connection.Dispatch(PlaywrightServerMessage message) in /_/src/Playwright/Transport/Connection.cs:line 267
```

[Example failing tests](https://github.com/martincostello/dotnet-playwright-tests/actions/runs/6545418680/attempts/1)

**Comment by mxschmitt** [comment]
My guess is that you are connecting to a BrowserStack server which is not matching with the client Playwright version. We have a lot of ConnectAsync tests as per [here](https://github.com/microsoft/playwright-dotnet/blob/main/src/Playwright.Tests/BrowserTypeConnectTests.cs) which are passing. This issue was raised a bunch of times already e.g. here https://github.com/microsoft/playwright/issues/27576 in the Node.js project.

As per [their docs](https://www.browserstack.com/docs/automate/playwright/browsers-and-os) they don't support the latest version, so this seems like a plausible cause. In the next version we prevent you from connecting to a version which is not supported. (does not match the minor version).

**Comment by martincostello** [comment]
BrowserStack sounds like a good root cause, though it doesn't fully explain why the `main` branch build immediately after updating Playwright didn't have the problem: [workflow](https://github.com/martincostello/dotnet-playwright-tests/actions/runs/6542629746)

**Comment by mxschmitt** [comment]
Maybe they gradually roll it out or they don't have it available on all the platforms yet. 

I tried to run Playwright for .NET v1.39.0 with a Playwright v1.38.0 server and it produced the same error, so I think there is no action on our side anymore. From the next release on, we will throw earlier instead of throwing null pointer exceptions.

<img width="1162" alt="image" src="https://github.com/microsoft/playwright-dotnet/assets/17984549/35ba86f1-d0cd-4098-bfa3-c6c8c4de8ece">

**Comment by mxschmitt** [comment]
Closing as per above.

**Comment by En3Tho** [comment]
Just stumbled upon this too. @mxschmitt I understand that technically this isn't really actionable but letting this being a `NullReferenceException` is a bad practice in my opinion. throwing something like `PlaywrightVersionMismatchException` or something like that could be a lot helpful.

**Comment by mxschmitt** [comment]
I think a couple of months later we added this check: https://github.com/microsoft/playwright/commit/fc32ca676bd26d6b8c386f6527aeeeba2998d77c

So this should not happen anymore.

**Comment by En3Tho** [comment]
It is really weird but I do still hit it with `Microsoft.Playwright, 1.47.0` nuget package and installed `playwright@1.47.0`. My case is running playwright from a docker image so maybe I'm missing something?

**Comment by mxschmitt** [comment]
Do you mind filing a new issue? Happy to debug it but we need reproduction steps.
