### ISSUE TITLE
[BUG] Cannot read incomplete UTF-16 JSON text as string with missing low surrogate

### ISSUE THREAD

**Issue by xyqlx** [microsoft/playwright-dotnet#2748]
### System info
- Playwright Version: v1.39.0
- Operating System: Windows 11
- Browser: Chromium
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Test file (self-contained)**

```cs
using Microsoft.Playwright;

using var playwright = await Playwright.CreateAsync();
await using var browser = await playwright.Chromium.LaunchAsync();
var page = await browser.NewPageAsync();
// this is a page on a Chinese video website
await page.GotoAsync("https://www.bilibili.com/video/BV1yR4y1C7KX");

var collections = await page.QuerySelectorAllAsync(".video-page-card-small");
foreach (var item in collections)
{
    var titleA = await item.QuerySelectorAsync(".info a .title");
    if (titleA != null)
    {
        Console.WriteLine(await titleA.InnerTextAsync());
    }
}
```

**Steps**
- Create the project following <https://playwright.dev/dotnet/docs/library#usage> and dotnet run.

**Expected**

No exceptions or I can handle it.

**Actual**

```text
Unhandled exception. Microsoft.Playwright.PlaywrightException: System.InvalidOperationException: Cannot read incomplete UTF-16 JSON text as string with missing low surrogate.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ReadIncompleteUTF16()
   at System.Text.Json.JsonReaderHelper.TryUnescape(ReadOnlySpan`1 source, Span`1 destination, Int32 idx, Int32& written)
   at System.Text.Json.JsonReaderHelper.GetUnescapedString(ReadOnlySpan`1 utf8Source)
   at System.Text.Json.JsonDocument.GetString(Int32 index, JsonTokenType expectedType)
   at System.Text.Json.JsonElement.ToString()
   at Microsoft.Playwright.Transport.Channels.ElementHandleChannel.OnMessage(String method, Nullable`1 serverParams) in /_/src/Playwright/Transport/Channels/ElementHandleChannel.cs:line 55
   at Microsoft.Playwright.Transport.Connection.Dispatch(PlaywrightServerMessage message) in /_/src/Playwright/Transport/Connection.cs:line 302
   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](ChannelOwnerBase object, String method, Dictionary`2 dictionary, Boolean keepNulls) in /_/src/Playwright/Transport/Connection.cs:line 132
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 516
   at Microsoft.Playwright.Core.Browser.CloseAsync() in /_/src/Playwright/Core/Browser.cs:line 79
   at Program.<Main>$(String[] args) in C:\project\PlaywrightDemo\PlaywrightDemo\Program.cs:line 10
   at Program.<Main>(String[] args)
```

if I catch this Exception

```cs
using Microsoft.Playwright;

using var playwright = await Playwright.CreateAsync();
await using var browser = await playwright.Chromium.LaunchAsync();
var page = await browser.NewPageAsync();
// this is a page on a Chinese video website
await page.GotoAsync("https://www.bilibili.com/video/BV1yR4y1C7KX");

var collections = await page.QuerySelectorAllAsync(".video-page-card-small");
foreach (var item in collections)
{
    try
    {
        var titleA = await item.QuerySelectorAsync(".info a .title");
        if (titleA != null)
        {
            Console.WriteLine(await titleA.InnerTextAsync());
        }
    }
    catch (PlaywrightException) { }
}
```

The connection will dispose after the above exception is triggered, making it difficult to handle the exception.

```text
Unhandled exception. Microsoft.Playwright.PlaywrightException: Connection disposed
   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](ChannelOwnerBase object, String method, Dictionary`2 dictionary, Boolean keepNulls) in /_/src/Playwright/Transport/Connection.cs:line 132
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 516
   at Microsoft.Playwright.Core.Browser.CloseAsync() in /_/src/Playwright/Core/Browser.cs:line 79
   at Program.<Main>$(String[] args) in C:\project\PlaywrightDemo\PlaywrightDemo\Program.cs:line 10
   at Program.<Main>(String[] args)
```

For reference, the TypeScript version is provided. This version will not raise exception.

```typescript
// following https://playwright.dev/docs/intro
import { test, expect } from '@playwright/test';

test('has title', async ({ page, browserName }) => {
  await page.goto('https://www.bilibili.com/video/BV1yR4y1C7KX');
  const collections = await page.$$('.video-page-card-small');
  for(const collection of collections){
    const title = await collection.$('.info a .title');
    console.log(browserName + ':' + await title?.innerText());
  }

  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle('洗脑神曲《𝓞𝓷𝓮 𝓚𝓲𝓼𝓼》，无法超越的绝美画面！！_哔哩哔哩_bilibili');
});
```

**Comment by mxschmitt** [comment]
Should be fixed with the next version as per https://github.com/microsoft/playwright/commit/5f527fedb1f6893219b69d735b1a9cdd81ad1466
