### ISSUE TITLE
[Bug]: Retrieving webpage information leads to continuously increasing memory usage and the webpage experiencing lagging

### ISSUE THREAD

**Issue by xyqlx** [microsoft/playwright-dotnet#2883]
### Version

1.42.0

### Steps to reproduce

steps to reproduce:
1. dotnet new console
2. add package and install Playwright
3. edit Program.cs. Note that since the target website is a live streaming platform, you need to fill in the live room that is currently broadcasting.
```csharp
using Microsoft.Playwright;
using System.Diagnostics;
using System.Runtime.InteropServices;

// windows only
if (!RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
{
    throw new PlatformNotSupportedException("This program only supports Windows");
}
var playwright = await Playwright.CreateAsync();
// I also tried Chromium
var browser = await playwright.Firefox.LaunchAsync(new BrowserTypeLaunchOptions
{
    Headless = true
});
List<string> watchedProcessNames = new List<string>{
    "node",
    "chrome",
    "firefox",
};
string recordPath = DateTime.Now.ToString("yyyy-MM-dd-HH-mm-ss") + ".txt";
var playPage = await browser.NewPageAsync();
// Open a live room that is currently broadcasting with some bullet screen comments on https://live.bilibili.com/, and then find its live ID in the URL.
int liveId = 47867;
await playPage.GotoAsync($"https://live.bilibili.com/{liveId}");
// await playPage.GotoAsync("http://127.0.0.1:5500/danmaku.html");
List<(string username, string content)> danmakuPool = new();
Timer timer = new Timer(async _ =>
{
    var chatItemsContainer = await playPage.QuerySelectorAsync("#chat-items");
    // check null
    if (chatItemsContainer == null)
    {
        Console.WriteLine("chatItemsContainer is null");
        return;
    }
    var chatItems = await chatItemsContainer.QuerySelectorAllAsync(".chat-item");
    var danmakus = (await Task.WhenAll(chatItems.Select(async (item) =>
    {
        try
        {
            var username = await item.GetAttributeAsync("data-uname");
            var content = await item.GetAttributeAsync("data-danmaku");
            return (username, content);
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
            return (null, null);
        }
    }))).Where(x => x.username != null && x.content != null).Cast<(string username, string content)>().ToList();
    var lastLength = danmakuPool.Count;
    // print new danmaku
    danmakuPool.AddRange(danmakus.Where(x => !danmakuPool.Contains(x)));
    var newDanmakuLength = danmakuPool.Count - lastLength;
    // limit danmakuPool length
    if (danmakuPool.Count > 200)
    {
        danmakuPool.RemoveRange(0, danmakuPool.Count - 200);
    }
    foreach (var danmaku in danmakuPool.Skip(danmakuPool.Count - newDanmakuLength))
    {
        Console.WriteLine($"{danmaku.username}: {danmaku.content}");
    }
    // record memory usage
    List<Process> watchedProcesses = Process.GetProcesses().Where(x => watchedProcessNames.Contains(x.ProcessName)).ToList();
    if (watchedProcesses.Count > 0)
    {
        string newContent = "";
        newContent += $"[{DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss")}]" + Environment.NewLine;
        foreach (var process in watchedProcesses)
        {
            newContent += $"{process.ProcessName}({process.Id}) {process.WorkingSet64 / 1024.0 / 1024.0: 0.00} MB" + Environment.NewLine;
        }
        using (StreamWriter sw = new StreamWriter(recordPath, true))
        {
            sw.WriteLine(newContent);
        }
    }
}, null, 0, 1000);
Console.WriteLine("Press any key to exit");
Console.ReadKey();
```
4. dotnet run

### Expected behavior

Program runs normally.

### Actual behavior

After a period of time (in the example below, about 7 minutes later), exception occurs when GetAttributeAsync.
It is observed that the memory usage of Firefox and Node.js keeps increasing.

![2024-03-13-18-30-12 txt](https://github.com/microsoft/playwright-dotnet/assets/40012783/3a8bdb3f-d9b5-4708-9d70-cf98034eedaa)

Exceptions:
```text
System.TimeoutException: Timeout 30000ms exceeded.
Call log:
  - waiting for Locator(":scope")
   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](ChannelOwner object, String method, Dictionary`2 dictionary, Boolean keepNulls) in /_/src/Playwright/Transport/Connection.cs:line 206
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 526
   at Microsoft.Playwright.Core.ElementHandle.GetAttributeAsync(String name) in /_/src/Playwright/Core/ElementHandle.cs:line 290
   at Program.<>c.<<<Main>$>b__0_3>d.MoveNext() in C:\project\BilibiliValidation\Program.cs:line 43
```

### Additional context

I also considered writing a webpage locally to reproduce the issue. In fact, there was indeed an issue where the Node.js process did not release memory, but the speed was relatively slow, and the browser process behaved normally. Below are the results and code I obtained on the local webpage.

![2024-03-13-18-48-30 txt](https://github.com/microsoft/playwright-dotnet/assets/40012783/880d3ae8-c94b-48f8-845a-127737d519d4)

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .chat-item {
            margin: 5px;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }
    </style>
</head>

<body>
    <div id="chat-items"></div>

    <script>
        function generateRandomText(length) {
            let result = '';
            const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
            const charactersLength = characters.length;
            for (let i = 0; i < length; i++) {
                result += characters.charAt(Math.floor(Math.random() * charactersLength));
            }
            const time = new Date().toLocaleTimeString();
            return time + ' ' + result;
        }

        function addChatItems() {
            const chatItemsContainer = document.getElementById('chat-items');
            for (let i = 0; i < 3; i++) {
                const newChatItem = document.createElement('div');
                newChatItem.classList.add('chat-item');
                newChatItem.textContent = generateRandomText(10);
                newChatItem.setAttribute('data-uname', 'alice');
                newChatItem.setAttribute('data-danmaku', newChatItem.textContent)
                chatItemsContainer.append(newChatItem);
            }

            const chatItems = document.querySelectorAll('.chat-item');
            if (chatItems.length > 50) {
                for (let i = 0; i < chatItems.length - 50; i++) {
                    chatItems[i].remove();
                }
            }
        }

        setInterval(addChatItems, 1000);
    </script>
</body>

</html>
```

### Environment

```Text
- Operating System: Windows 11 23H2
- CPU: x64
- Browser: Firefox
- .NET Version (TFM): net8.0
```

**Comment by mxschmitt** [comment]
I see that you create a lot of ElementHandles and never dispose them, so you should do e.g.:

```csharp
    await Task.WhenAll(watchedProcesses.Select(x => { x.Dispose(); return Task.CompletedTask; }));
    await Task.WhenAll(chatItems.Select(item => item.DisposeAsync().AsTask()));
    await chatItemsContainer.DisposeAsync();
```

Also we strongly discourage ElementHandles, as per [here](https://playwright.dev/docs/handles#locator-vs-elementhandle). You should rewrite it using [Locators](https://playwright.dev/docs/locators) doing e.g. this, then you don't have such problems.

```csharp
using Microsoft.Playwright;
using System.Diagnostics;
using System.Runtime.InteropServices;

// windows only
if (!RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
{
    throw new PlatformNotSupportedException("This program only supports Windows");
}
var playwright = await Playwright.CreateAsync();
// I also tried Chromium
var browser = await playwright.Firefox.LaunchAsync(new BrowserTypeLaunchOptions
{
    Headless = true
});
List<string> watchedProcessNames = new List<string>{
    "node",
    "chrome",
    "firefox",
};
string recordPath = DateTime.Now.ToString("yyyy-MM-dd-HH-mm-ss") + ".txt";
var playPage = await browser.NewPageAsync();
// Open a live room that is currently broadcasting with some bullet screen comments on https://live.bilibili.com/, and then find its live ID in the URL.
int liveId = 47867;
//await playPage.GotoAsync($"https://live.bilibili.com/{liveId}");
await playPage.GotoAsync("http://127.0.0.1:8080/index.html");
List<(string username, string content)> danmakuPool = new();
Timer timer = new Timer(async _ =>
{
    var chatItemsContainer = playPage.Locator("#chat-items");
    if (await chatItemsContainer.IsHiddenAsync())
    {
        Console.WriteLine("chatItemsContainer is null");
        return;
    }
    var chatItems = await chatItemsContainer.Locator(".chat-item").AllAsync();
    var danmakus = (await Task.WhenAll(chatItems.Select(async (item) =>
    {
        try
        {
            var username = await item.GetAttributeAsync("data-uname");
            var content = await item.GetAttributeAsync("data-danmaku");
            return (username, content);
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
            return (null, null);
        }
    }))).Where(x => x.username != null && x.content != null).Cast<(string username, string content)>().ToList();
    var lastLength = danmakuPool.Count;
    // print new danmaku
    danmakuPool.AddRange(danmakus.Where(x => !danmakuPool.Contains(x)));
    var newDanmakuLength = danmakuPool.Count - lastLength;
    // limit danmakuPool length
    if (danmakuPool.Count > 200)
    {
        danmakuPool.RemoveRange(0, danmakuPool.Count - 200);
    }
    foreach (var danmaku in danmakuPool.Skip(danmakuPool.Count - newDanmakuLength))
    {
        Console.WriteLine($"{danmaku.username}: {danmaku.content}");
    }
    // record memory usage
    List<Process> watchedProcesses = Process.GetProcesses().Where(x => watchedProcessNames.Contains(x.ProcessName)).ToList();
    if (watchedProcesses.Count > 0)
    {
        string newContent = "";
        newContent += $"[{DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss")}]" + Environment.NewLine;
        foreach (var process in watchedProcesses)
        {
            newContent += $"{process.ProcessName}({process.Id}) {process.WorkingSet64 / 1024.0 / 1024.0: 0.00} MB" + Environment.NewLine;
        }
        using (StreamWriter sw = new StreamWriter(recordPath, true))
        {
            sw.WriteLine(newContent);
        }
    }
    await Task.WhenAll(watchedProcesses.Select(x => { x.Dispose(); return Task.CompletedTask; }));
}, null, 0, 1000);
Console.WriteLine("Press any key to exit");
Console.ReadKey();
```

this seems to fix the memory leak for me.

**Comment by xyqlx** [comment]
Thank you for your reply @mxschmitt , I have tried the two suggested solutions, and they work well on the local webpage I provided. However, unfortunately, they still exhibit abnormal memory usage growth on live.bilibili.com.

Here are some of my running results. I tried the following:
1. Ran the code with Dispose code for ElementHandles once on live.bilibili.com.
2. I modified it to use Locator and ran it once locally and twice on live.bilibili.com (until it exited due to an exception).

The chart below shows the logs plotted for these four runs:

![dispose_bilibili txt](https://github.com/microsoft/playwright-dotnet/assets/40012783/532c33b9-9020-4ccb-8493-1a8c39e4e77e)

![locator_local txt](https://github.com/microsoft/playwright-dotnet/assets/40012783/5b78a49f-360f-4a37-bf8b-669b015e205d)

![locator_bilibili txt](https://github.com/microsoft/playwright-dotnet/assets/40012783/67f721fa-68c1-4a55-a74a-bf39e612c304)

![locator_bilibili_2nd txt](https://github.com/microsoft/playwright-dotnet/assets/40012783/93d2cd3c-ba10-4ef4-bdfd-31958838d0ca)

The last two runs exited due to an exception, and the messages are as follows:

```text
System.TimeoutException: Timeout 30000ms exceeded.
Call log:
  - waiting for Locator("#chat-items").Locator(".chat-item").Nth(15)
   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](ChannelOwner object, String method, Dictionary`2 dictionary, Boolean keepNulls) in /_/src/Playwright/Transport/Connection.cs:line 206
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 526
   at Microsoft.Playwright.Core.Frame.GetAttributeAsync(String selector, String name, FrameGetAttributeOptions options) in /_/src/Playwright/Core/Frame.cs:line 384
   at Program.<>c.<<<Main>$>b__0_4>d.MoveNext() in C:\project\BilibiliValidation\Program.cs:line 42
```

As a supplement, the code for my Locator version:

```csharp
using Microsoft.Playwright;
using System.Diagnostics;
using System.Runtime.InteropServices;

// windows only
if (!RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
{
    throw new PlatformNotSupportedException("This program only supports Windows");
}
var playwright = await Playwright.CreateAsync();
// I also tried Chromium
var browser = await playwright.Firefox.LaunchAsync(new BrowserTypeLaunchOptions
{
    Headless = true
});
List<string> watchedProcessNames = new List<string>{
    "node",
    "chrome",
    "firefox",
};
string recordPath = DateTime.Now.ToString("yyyy-MM-dd-HH-mm-ss") + ".txt";
var playPage = await browser.NewPageAsync();
// Open a live room that is currently broadcasting with some bullet screen comments on https://live.bilibili.com/, and then find its live ID in the URL.
int liveId = 47867;
await playPage.GotoAsync($"https://live.bilibili.com/{liveId}");
// await playPage.GotoAsync("http://127.0.0.1:5500/danmaku.html");
List<(string username, string content)> danmakuPool = new();
Timer timer = new Timer(async _ =>
{
    var chatItemsContainer = playPage.Locator("#chat-items");
    // check null
    if (await chatItemsContainer.IsHiddenAsync())
    {
        Console.WriteLine("chatItemsContainer is hidden");
        return;
    }
    var chatItems = await chatItemsContainer.Locator(".chat-item").AllAsync();
    var danmakus = (await Task.WhenAll(chatItems.Select(async (item) =>
    {
        try
        {
            var username = await item.GetAttributeAsync("data-uname");
            var content = await item.GetAttributeAsync("data-danmaku");
            return (username, content);
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
            return (null, null);
        }
    }))).Where(x => x.username != null && x.content != null).Cast<(string username, string content)>().ToList();
    var lastLength = danmakuPool.Count;
    // print new danmaku
    danmakuPool.AddRange(danmakus.Where(x => !danmakuPool.Contains(x)));
    var newDanmakuLength = danmakuPool.Count - lastLength;
    // limit danmakuPool length
    if (danmakuPool.Count > 200)
    {
        danmakuPool.RemoveRange(0, danmakuPool.Count - 200);
    }
    foreach (var danmaku in danmakuPool.Skip(danmakuPool.Count - newDanmakuLength))
    {
        Console.WriteLine($"{danmaku.username}: {danmaku.content}");
    }
    // record memory usage
    List<Process> watchedProcesses = Process.GetProcesses().Where(x => watchedProcessNames.Contains(x.ProcessName)).ToList();
    if (watchedProcesses.Count > 0)
    {
        string newContent = "";
        newContent += $"[{DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss")}]" + Environment.NewLine;
        foreach (var process in watchedProcesses)
        {
            newContent += $"{process.ProcessName}({process.Id}) {process.WorkingSet64 / 1024.0 / 1024.0: 0.00} MB" + Environment.NewLine;
        }
        using (StreamWriter sw = new StreamWriter(recordPath, true))
        {
            sw.WriteLine(newContent);
        }
    }
    await Task.WhenAll(watchedProcesses.Select(x => { x.Dispose(); return Task.CompletedTask; }));
}, null, 0, 1000);
Console.WriteLine("Press any key to exit");
Console.ReadKey();
```

**Comment by xyqlx** [comment]
I tried another approach (EvaluateAsync) and solved the original problem.

![2024-03-24-01-12-45 txt](https://github.com/microsoft/playwright-dotnet/assets/40012783/429a5aeb-e8ba-4d3e-bd6b-8aaa85e76e00)

Relevant code:

```csharp
JsonElement? danmakuJson = await playPage.EvaluateAsync(@"[...document.querySelectorAll('.chat-item')].map(x=>({'username': x.getAttribute('data-uname'), 'content': x.getAttribute('data-danmaku')}))");
    if (danmakuJson == null || danmakuJson.Value.ValueKind != JsonValueKind.Array)
    {
        return;
    }
var danmakus = danmakuJson.Value.EnumerateArray()
    .Where(x=>x.ValueKind == JsonValueKind.Object
        && x.TryGetProperty("username", out var username)
        && x.TryGetProperty("content", out var content)
        && username.ValueKind == JsonValueKind.String
        && content.ValueKind == JsonValueKind.String)
    .Select(x => (username: x.GetProperty("username").GetString()!, content: x.GetProperty("content").GetString()!))
    .ToList();
```

**Comment by mxschmitt** [comment]
The workaround makes sense, since it goes entirely different code paths internally then.

Does this happen with Firefox only? Have you tried Chrome? Might be a bug when we talk to Firefox that we don't clear the handles somewhere.;;

**Comment by xyqlx** [comment]
Yes, I have tried Chrome. @mxschmitt 
![chrome_locator_bilibili txt](https://github.com/microsoft/playwright-dotnet/assets/40012783/449a29b0-a321-4991-9393-e2efbbd808f0)
