### ISSUE TITLE
[Bug]: 'The parameter is incorrect' at System.ConsolePal.SetConsoleInputEncoding(Encoding enc)

### ISSUE THREAD

**Issue by adamwoods1vitalitycouk** [microsoft/playwright-dotnet#2888]
### Version

1.42.0

### Steps to reproduce

Install Rider version 2022.3.0
Install Rider version 2023.3.4
Within any project, **Debug** (Not run) a test with the following line of code
`var playwright = await Playwright.CreateAsync();`

### Expected behavior

Playwright to initialise in both versions when run in debug mode.

### Actual behavior

Playwright raises an exception but only in Rider 2023.3.4 when in debug mode,

### Additional context

**Exception thrown**
```
System.IO.IOException: The parameter is incorrect.
   at System.ConsolePal.SetConsoleInputEncoding(Encoding enc)
   at System.Console.set_InputEncoding(Encoding value)
   at Microsoft.Playwright.Transport.StdIOTransport.StartProcessWithUTF8IOEncoding(Process process) in /_/src/Playwright/Transport/StdIOTransport.cs:line 175
   at Microsoft.Playwright.Transport.StdIOTransport..ctor() in /_/src/Playwright/Transport/StdIOTransport.cs:line 47
   at Microsoft.Playwright.Playwright.CreateAsync() in /_/src/Playwright/Playwright.cs:line 43
   at SalesforceServicingOrg.Foundation.Hooks.CommonHooks.BeforeScenario() in D:\Users\adam.woods\RiderProjects\salesforceservicingorg.ui.tests\SalesforceServicingOrg.Foundation\Hooks\CommonHooks.cs:line 31
```

**Additional**
We are unable to start any tests with a parameter is incorrect in StdIOTransport.cs:line 175. The issue seems to be encoding from the console. Although despite all Windows and Rider settings pointing to encoding that matches UTF-8 - we still seem to hit this.  We can execute tests in run mode, but not in debug mode. There appears to be no obvious settings that have changed between Rider versions - but it is unclear where Playwright gets the encoding setting from. Out of 6 team members, only 1 can run in the latest Rider version.

### Environment

```shell
System:
    OS: Windows 10 10.0.17763
    CPU: (4) x64 Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
    Memory: 7.24 GB / 16.00 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    VSCode: 1.26.1 - C:\Program Files\Microsoft VS Code\bin\code.CMD


Rider 2022.3.0
Rider 2023.3.4
```

**Comment by adamwoods1vitalitycouk** [comment]
Thanks @yury-s ,two files attached.

[ExampleProject.zip](https://github.com/microsoft/playwright-dotnet/files/14653510/ExampleProject.zip)
Sample project which is failing. _NUnit 3 is targeted but the same happens for NUnit 4, so considered out of scope._

https://github.com/microsoft/playwright-dotnet/assets/137996986/45020233-266b-4bf2-9d61-e08d0064e9b8
A recording showing me debug a test in newer and older versions of Rider at the same time. Might be helpful.

Cheers

**Comment by mxschmitt** [comment]
I extracted the project and ran `dotnet test` and it works for me. Also I tried it with Rider 2023.3.4 which works for me.

<img width="1012" alt="image" src="https://github.com/microsoft/playwright-dotnet/assets/17984549/68169f57-4dfc-43a3-8160-618c0fabffec">

Could your coworker try to execute the following and see what it yields to?

```csharp
        var encoding = new UTF8Encoding(false);
        Console.WriteLine(encoding.CodePage); // This should print 65001
        Console.InputEncoding = encoding;
        Console.OutputEncoding = encoding;  
        var microsoftPage = new MicrosoftPage();
        await microsoftPage.DoTheWork();
```

This is the code which should fail for him in isolation.

**Comment by adamwoods1vitalitycouk** [comment]
Hi @mxschmitt, thanks for the quick reply again.

**Worth noting that running 'Dotnest Test' will not produce the issue, this is specifically only triggered when using debug within Rider.**

Either way, interestingly, your code suggestion provides a good workaround. The browser is successful in loading. 

I went a step further to debug this and outputted the encoding before and after setting it manually. You can see that the encoding set by Rider is System.Text.OSEncoding, despite windows and all other rider settings pointing to UTF8. It seems that OSEncoding cannot allow Playwright to run, but there seems no setting in Rider to move it over to outputting UTF8 by default that works for me.

![image](https://github.com/microsoft/playwright-dotnet/assets/137996986/90b0c84d-1963-4931-9f52-98c8327394cf)
```
        var inputOriginal = Console.InputEncoding;
        var outputOriginal = Console.OutputEncoding;

        var encoding = new UTF8Encoding(false);
        Console.InputEncoding = encoding;
        Console.OutputEncoding = encoding;

        var inputNew = Console.InputEncoding;
        var outputNew = Console.OutputEncoding;

        Console.WriteLine(inputOriginal); // This should print 65001
        Console.WriteLine(outputOriginal); // This should print 65001
        Console.WriteLine(inputNew); // This should print 65001
        Console.WriteLine(outputNew); // This should print 65001

        var microsoftPage = new MicrosoftPage();
        await microsoftPage.DoTheWork();
```

Interesting to know your thoughts on this? It seems we are narrowing down on the issue. It is an encoding issue that seems to stem from Rider, but without knowing where Playwright is getting the setting from - I am unsure how to move forward other than to use the workaround above.

Thanks in advance
Adam

**Comment by mxschmitt** [comment]
Yeah I tried debug mode in Rider which was working for me. Weirdly the code above from me was more for testing rather than a workaround, thats exactly what we [do internally](https://github.com/microsoft/playwright-dotnet/blob/d20b160777a624a9bfbde86740914aa4d3ae305d/src/Playwright/Transport/StdIOTransport.cs#L162) which throws for some reason for some of your peers.

So I'm curious - why does it work if we execute it in isolation rather than inside our library?

Could you try to log the `CodePage` property? Since thats what the .NET runtime does internally which throws: https://github.com/dotnet/runtime/blob/e12e2fa6cbdd1f4b0c8ad1b1e2d960a480c21703/src/libraries/System.Console/src/System/ConsolePal.Windows.cs#L106

**Comment by adamwoods1vitalitycouk** [comment]
Is this what you mean @mxschmitt ?
![image](https://github.com/microsoft/playwright-dotnet/assets/137996986/6507de70-4419-4017-9491-f10e9bd9373c)

**Comment by mxschmitt** [comment]
Yeah, but does this make it work? Thats super weird, because these are just `Console.WriteLine` statements which should not change any behaviour.

**Comment by adamwoods1vitalitycouk** [comment]
No - this does not solve anything. Apologies for the confusion.

The only way currently to get a test to run in debug is to add the following lines
 var encoding = new UTF8Encoding(false);
Console.InputEncoding = encoding;
Console.OutputEncoding = encoding;

Otherwise, without this - coding is always set to OSEncoding and debug fails.

**Comment by mxschmitt** [comment]
What I don't understand is the following:

- The error shows clearly, that it throws [here](https://github.com/microsoft/playwright-dotnet/blob/d20b160777a624a9bfbde86740914aa4d3ae305d/src/Playwright/Transport/StdIOTransport.cs#L162). So we reach the function and `hasConsole` is true.
- Why does it work if you execute the _same code_ (from my understanding) manually outside of the library? There it does not throw for some reason. So it seems like Rider does some magic? Do you have a breakpoint set in a special place or something like that? Maybe some special terminal options? I'm unfortunately not familiar with the Rider IDE.

**Comment by domwvitality** [comment]
Hi @mxschmitt 

The error is appearing on this line - https://github.com/microsoft/playwright-dotnet/blob/d20b160777a624a9bfbde86740914aa4d3ae305d/src/Playwright/Transport/StdIOTransport.cs#L175

@adamwoods1vitalitycouk can get his tests working by updating the encoding to use  `var encoding = new UTF8Encoding(false);` prior to starting Playwright. 

The issue looks like it's specific to setting the `Console.InputEncoding` to `System.Text.OSEncoding` which is the original value. Not sure what the impact would be but could using `Encoding.Default` be safer to ensure it's getting reverted back to an accepted value?

**Comment by mxschmitt** [comment]
I see, that makes sense now! I miss-read the line line numbers - so its throwing when we restore it back how it was.

Maybe the most reasonable thing on our side to workaround this is by adding a try/catch around it, so its like a best-effort approach.

cc @nohwnd
