### ISSUE TITLE
[Bug]: error code: STATUS_STACK_BUFFER_OVERRUN

### ISSUE THREAD

**Issue by Logical05** [microsoft/playwright-dotnet#2942]
### Version

1.44.0

### Steps to reproduce

I'm making a wpf app and testing playwright using this simple code to run but I'm getting an error that says the page crashed on my friend's computer but mine is fine.

Code:

     using var playwright = await Playwright.CreateAsync();
     await using var browser = await playwright.Chromium.LaunchAsync(new() { Headless = false });
     var page = await browser.NewPageAsync();
     await page.GotoAsync("https://www.microsoft.com", new PageGotoOptions { WaitUntil = WaitUntilState.DOMContentLoaded });

Error:
![Screenshot 2024-06-01 003422](https://github.com/microsoft/playwright-dotnet/assets/85784528/aac6c92f-bd81-492c-af39-7d646d7a0f37)

### Expected behavior

I want to enter the website

### Actual behavior

Microsoft.Playwright.PlaywrightException: Page crashed
Call log:
  - navigating to "https://www.microsoft.com", waiting until "domcontentloaded" at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](ChannelOwner object, String method, Dictionary 2 dictionary, Boolean keepNulls) in /_/src/Playwright/Transport/Connection.cs:line 206 
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 532 
   at Microsoft.Playwright.Core.Frame.GotoAsync(String url, FrameGotoOptions options) in /_/src/Playwright/Core/Frame.cs:line 791
   at MPAS.UserControls.DashboardUserControl.Login(String link, CancellationToken token, String storagePath) in C:\Users\Username\Downloads\MPAS\UserControls\DashboardUserControl.xaml.cs:line 197

### Environment

```Text
- Operating System: [Windows 11 Pro]
- Browser: [Chromium 125.0.6422.26 (Developer Build) (64-bit) ]
- .NET Version (TFM): [net8.0]
```

**Comment by Logical05** [comment]
I don't know why. But I advised my friend to reinstall windows and it fixed it.
