### ISSUE TITLE
[Bug]: TearDown : System.InvalidOperationException : Collection was modified; enumeration operation may not execute. OR Microsoft.Playwright.TargetClosedException : Target page, context or browser has been closed

### ISSUE THREAD

**Issue by Kedar-Ghadge** [microsoft/playwright-dotnet#2979]
### Version

1.44.0

### Steps to reproduce
Parallel test execution is failing for the multiple tests under same test class.

1. Clone my repo at https://github.com/Kedar-Ghadge/PlaywrightWithNunitCSharp.git
2. execute command `dotnet test` from the project's folder path
3. You should see the error come up(sometimes it may random and reproduce on execution after 4-5 times)

### Expected behavior

- Tests should execute smoothly in parallel without any exception

### Actual behavior

If I keep 4 or more tests in single class and executing it parallelly then frequently getting errors on any alternate tests:

```
TearDown : System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
--TearDown
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at Microsoft.Playwright.NUnit.BrowserTest.BrowserTearDown() in /_/src/Playwright.NUnit/BrowserTest.cs:line 55
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUpOrTearDownMethod(TestExecutionContext context, IMethodInfo method)
   at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunTearDown(TestExecutionContext context)
```
OR
```
Microsoft.Playwright.TargetClosedException : Target page, context or browser has been closed
   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](ChannelOwner object, String method, Dictionary`2 dictionary, Boolean keepNulls) in /_/src/Playwright/Transport/Connection.cs:line 206
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 532
   at Microsoft.Playwright.Core.Page.ScreenshotAsync(PageScreenshotOptions options) in /_/src/Playwright/Core/Page.cs:line 675
   at MyTests.Utilities.Traces.AllureScreenshot.TakeAllureScreenshot(IPage page, String stepDetail, Status status) in C:\Users\kedarg\Documents\Project\AutomationTool\MGB-Member-Portal-Automation\MyTests\Utilities\Traces\AllureScreenshot.cs:line 19
   at MyTests.Tests.Sections.LoginTests.LoginTest.LogInInfo(Login login) in C:\Users\kedarg\Documents\Project\AutomationTool\MGB-Member-Portal-Automation\MyTests\Tests\Sections\LoginTests\LoginTest.cs:line 170
   at Allure.Net.Commons.Steps.AllureAbstractStepAspect.WrapAsync(Func`2 target, Object[] args, MethodBase metadata, String stepName, List`1 stepParameters)
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.DelegatingTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
```

### Additional context

- This is very random behavior and I have already used ` .ToList()`  for each of my foreach loop.
-  Even if I write or avoid `TeardDown` it doesn't create any difference.
- Creating a separate page was not feasible solution still tried that as well but again frequency of issue reduced but still it was occurring.

### Environment

```Text
- Operating System: [Windows 11]
- CPU: [x64]
- Browser: [All, Chromium, Firefox, WebKit]
- .NET Version (TFM): [net8.0]
- Other info:
```

**Comment by akshaysarode31** [comment]
I am facing a somewhat similar issue. Not sure what the reason is

**Comment by mxschmitt** [comment]
Do you mind sharing a reproduction which we can run locally? Ideally a small Git repository.

**Comment by akshaysarode31** [comment]
> Do you mind sharing a reproduction which we can run locally? Ideally a small Git repository. That would be essencial for us to act on issues like this.

https://github.com/akshaysarode31/PlaywrightFramework.git

this is the link to my repo.
If you run all the test cases, you will get a similar error

**Comment by Kedar-Ghadge** [comment]
> Do you mind sharing a reproduction which we can run locally? Ideally a small Git repository. That would be essencial for us to act on issues like this.

@mxschmitt , sharing a small git repo, where this issue is reproducible you will get both of the above mentioned errors,
https://github.com/Kedar-Ghadge/PlaywrightWithNunitCSharp.git

**Comment by mxschmitt** [comment]
Your repro is different in terms of how it uses parallelism, we as of today [only support self](https://playwright.dev/dotnet/docs/test-runners#running-nunit-tests-in-parallel):

```diff
diff --git a/PlaywrightWithNunitCSharp/PlaywrightWithNunitCSharp/LoginTest.cs b/PlaywrightWithNunitCSharp/PlaywrightWithNunitCSharp/LoginTest.cs
index cb708f6..5e73799 100644
--- a/PlaywrightWithNunitCSharp/PlaywrightWithNunitCSharp/LoginTest.cs
+++ b/PlaywrightWithNunitCSharp/PlaywrightWithNunitCSharp/LoginTest.cs
@@ -7,7 +7,7 @@ using System.Text.RegularExpressions;
 
 namespace PlaywrightWithNunitCSharp
 {
-  [Parallelizable(ParallelScope.All)]
+  [Parallelizable(ParallelScope.Self)]
   [TestFixture]
   public class Tests : PageTest
   {
```
